export type ChecklistPriority = "critical" | "important" | "good-to-have";

export interface ChecklistReference {
  label: string;
  url: string;
}

export interface ChecklistItem {
  id: string;
  title: string;
  description: string;
  why: string;
  how: string;
  priority: ChecklistPriority;
  appLink?: string;
  appLinkLabel?: string;
  /** Detailed guide fields (expanded view) */
  requirements?: string[];
  steps?: string[];
  fees?: string;
  processingTime?: string;
  tips?: string[];
  references?: ChecklistReference[];
}

export interface ChecklistPhase {
  id: string;
  number: number;
  title: string;
  subtitle: string;
  color: string;
  bg: string;
  borderColor: string;
  items: ChecklistItem[];
}

export const CHECKLIST_PHASES: ChecklistPhase[] = [
  {
    id: "government-ids",
    number: 1,
    title: "Government IDs & Registration",
    subtitle: "The documents you need before anything else.",
    color: "text-blue-600 dark:text-blue-400",
    bg: "bg-blue-500/10",
    borderColor: "border-blue-500/30",
    items: [
      {
        id: "tin",
        title: "Get your TIN from BIR",
        description: "Your Tax Identification Number is required for employment, banking, business registration, and almost every government transaction.",
        why: "You legally cannot be employed or open most bank accounts without a TIN. Having multiple TINs is a criminal offense with penalties up to ₱1,000 and/or imprisonment.",
        how: "If employed: your employer processes it via BIR Form 1902. If self-employed/freelancer: go to your local BIR Revenue District Office (RDO) with a valid ID and BIR Form 1901. Alternatively, use the BIR eRegistration portal at bir.gov.ph.",
        priority: "critical",
        appLink: "/tools/taxes",
        appLinkLabel: "BIR Tax Tracker",
        requirements: [
          "Any valid government-issued ID (passport, driver's license, PhilSys National ID, voter's ID)",
          "Birth certificate (PSA copy preferred)",
          "BIR Form 1902 (if employed — your employer usually provides this)",
          "BIR Form 1901 (if self-employed or freelancer)",
          "Marriage certificate (if applicable)",
          "1x1 or 2x2 photo (some RDOs require this)",
        ],
        steps: [
          "Determine your registration type: Employee (Form 1902), Self-Employed/Freelancer (Form 1901), or Mixed Income (Form 1901)",
          "If employed: Ask your HR/employer to process your TIN. They will submit Form 1902 to the RDO with jurisdiction over your employer's address",
          "If self-employed: Download BIR Form 1901 from bir.gov.ph or get a copy at any BIR office",
          "Fill out the form completely — use black ink, print legibly, and ensure your name matches your birth certificate exactly",
          "Visit the Revenue District Office (RDO) with jurisdiction over your home address (use the BIR RDO locator at bir.gov.ph)",
          "Submit the form with your requirements at the New Business Registrant (NBR) lane or TIN Issuance lane",
          "Wait for processing — you'll receive your TIN on the same day in most cases",
          "Online option: Go to orus.bir.gov.ph (Online Registration and Update System) and register as a new taxpayer. ORUS replaced the old eREG system",
        ],
        fees: "Free — TIN registration has no fees",
        processingTime: "Same day (walk-in) or 3-5 business days (online/employer-processed)",
        tips: [
          "NEVER apply for a second TIN — having multiple TINs is a criminal offense under the National Internal Revenue Code",
          "If you lost your TIN, go to any BIR office with a valid ID to retrieve it. You can also call the BIR hotline at 8538-3200",
          "Your TIN follows you for life — even if you change employers or RDOs, your TIN stays the same",
          "If applying online, make sure to verify your email. The confirmation is sent within 24 hours",
          "Keep a photo of your TIN card on your phone for quick reference",
        ],
        references: [
          { label: "BIR ORUS (Online Registration)", url: "https://orus.bir.gov.ph/" },
          { label: "BIR Official Website", url: "https://www.bir.gov.ph/" },
          { label: "BIR RDO Locator", url: "https://www.bir.gov.ph/rdo-locator" },
        ],
      },
      {
        id: "sss",
        title: "Register with SSS",
        description: "The Social Security System provides retirement pension, disability, maternity, sickness, and death benefits — plus salary and calamity loans.",
        why: "SSS is mandatory for all employees and voluntary for self-employed/OFWs. Your SSS number is required to be hired. Benefits compound over a lifetime of contributions — the more you put in, the higher your pension.",
        how: "Register online at my.sss.gov.ph with a valid ID and submit BIR Form SS-1. Your employer should process this for you if you're formally employed. After 36 monthly contributions, you can apply for a physical SS card or UMID.",
        priority: "critical",
        requirements: [
          "Any valid government-issued ID with photo and signature (passport, driver's license, PRC ID, voter's ID)",
          "Birth certificate (PSA-authenticated original or certified true copy)",
          "Filled-out SS Form E-1 (Personal Record) — available at SSS branches or downloadable from sss.gov.ph",
          "For employed: Employer SSS number (your HR department will provide this)",
          "1x1 ID photo (for the SS card)",
        ],
        steps: [
          "Go to the SSS website at sss.gov.ph and click 'Online Member Registration' under the e-Services menu",
          "Fill out the online SS Form E-1 — provide your personal info, contact details, and employment information",
          "Upload a scanned copy of your valid ID and birth certificate",
          "Submit the form — you'll receive a temporary SSS number via email immediately",
          "Print the confirmation page with your SS number",
          "To get a physical UMID card: Visit your nearest SSS branch with your confirmation, valid ID, and 1x1 photo after 36 months of contributions",
          "Alternative (walk-in): Visit any SSS branch, fill out SS Form E-1 at the counter, submit with requirements, and receive your SSS number same day",
          "Create your My.SSS online account at my.sss.gov.ph to view contributions, apply for loans, and track benefits",
        ],
        fees: "Free — SSS registration has no fees. UMID card is also free",
        processingTime: "SSS number: same day (online or walk-in). UMID card: 30-60 days after application",
        tips: [
          "Create your My.SSS account immediately after getting your number — it lets you track contributions, apply for loans online, and update your info",
          "If employed, verify that your employer is remitting your contributions monthly by checking My.SSS",
          "Keep your SSS number private — never share it on social media or with strangers",
          "You can start voluntary contributions even if you're not employed — minimum monthly contribution is around ₱600",
          "After 36 monthly contributions, you become eligible for SSS salary loans (up to 2 months' salary)",
        ],
        references: [
          { label: "SSS Online Registration", url: "https://www.sss.gov.ph/" },
          { label: "My.SSS Portal", url: "https://member.sss.gov.ph/" },
          { label: "SSS Contribution Schedule", url: "https://www.sss.gov.ph/contribution/" },
        ],
        appLink: "/tools/contributions",
        appLinkLabel: "Contributions Tracker",
      },
      {
        id: "philhealth",
        title: "Register with PhilHealth",
        description: "PhilHealth covers inpatient hospitalization, day surgery, outpatient consultations, and selected medicines through its benefits packages.",
        why: "A single hospitalization without PhilHealth coverage can cost ₱50,000–₱200,000+. PhilHealth significantly reduces your out-of-pocket expenses. Mandatory for employees; voluntary for self-employed and OFWs.",
        how: "If employed: employer enrolls you. Self-employed: register at the nearest PhilHealth office or through PhilSys. Bring a valid ID and complete PMRF (PhilHealth Member Registration Form). Check your contributions at philhealth.gov.ph.",
        priority: "critical",
        appLink: "/tools/contributions",
        appLinkLabel: "Contributions Tracker",
        requirements: [
          "Any valid government-issued ID with photo (passport, driver's license, PhilSys National ID, UMID, voter's ID, PRC ID)",
          "PSA-issued birth certificate (for verifying dependents)",
          "PhilHealth Member Registration Form (PMRF) — available at PhilHealth offices or downloadable from philhealth.gov.ph",
          "Active email address (for online registration)",
          "For employed: employer's PhilHealth Employer Number (PEN)",
          "For dependents: marriage certificate (spouse), birth certificates (children), or proof of guardianship",
        ],
        steps: [
          "Step 1 (Online): Go to the PhilHealth Electronic Registration System (ERSS) at memberinquiry.philhealth.gov.ph/member/pinApplication.xhtml",
          "Step 2: Fill out the online registration form with your personal details, contact info, and membership category (employed, self-employed, voluntary, etc.)",
          "Step 3: Upload scanned copies of your valid ID and supporting documents",
          "Step 4: Submit the form and wait for a confirmation email from PhilHealth",
          "Step 5: Click the confirmation link in the email to activate your account",
          "Step 6: You will receive your PhilHealth Identification Number (PIN) via email",
          "Alternative (walk-in): Download the PMRF from philhealth.gov.ph, fill it out, and submit it at the nearest PhilHealth Local Health Insurance Office (LHIO) with your valid ID",
          "If employed: Your employer will handle registration. Provide your PMRF to your HR department during onboarding",
          "Create your online member portal account at memberinquiry.philhealth.gov.ph to view contributions and membership status",
        ],
        fees: "Free — PhilHealth registration has no fees. Monthly contributions are based on your salary (5% of monthly basic salary, shared equally between employer and employee)",
        processingTime: "Online: 1-3 business days for PIN issuance. Walk-in: same day for PIN, ID card takes 30-60 days",
        tips: [
          "Under the Universal Health Care (UHC) Law, all Filipinos are automatically eligible for PhilHealth coverage — but you still need to register to get your PIN",
          "Premium rate for 2025 is 5% of monthly basic salary (capped at ₱5,000/month for those earning ₱100,000+)",
          "Minimum monthly contribution is ₱500 for voluntary and self-employed members",
          "PhilHealth covers inpatient care (case rates per diagnosis), outpatient consultations at accredited health facilities, and Z-benefits for catastrophic illnesses like cancer and kidney dialysis",
          "Always present your PhilHealth ID and Member Data Record (MDR) at hospital admission to ensure coverage",
          "OFWs can register through iRemit or Ventaja branches in their host country",
        ],
        references: [
          { label: "PhilHealth Official Website", url: "https://www.philhealth.gov.ph/" },
          { label: "PhilHealth Online Registration", url: "https://memberinquiry.philhealth.gov.ph/member/pinApplication.xhtml" },
          { label: "PhilHealth Member Portal", url: "https://memberinquiry.philhealth.gov.ph/member/" },
          { label: "PhilHealth Benefits Packages", url: "https://www.philhealth.gov.ph/benefits/" },
        ],
      },
      {
        id: "pagibig",
        title: "Register with Pag-IBIG (HDMF)",
        description: "Pag-IBIG provides housing loans, multi-purpose loans, and the MP2 savings program that earns 6–7% tax-free dividends annually.",
        why: "Mandatory for employees. The MP2 program alone consistently outperforms bank savings rates at 6–7% per year, fully tax-free. After 24 months of contributions, you're eligible for housing loans up to ₱6,000,000.",
        how: "Register at Virtual Pag-IBIG (pagibig-fund.gov.ph) or visit a branch. Bring a valid ID and fill out the Membership Registration Form (MRF). Employer handles mandatory contributions from payroll.",
        priority: "critical",
        appLink: "/tools/contributions",
        appLinkLabel: "Contributions Tracker",
        requirements: [
          "Any valid government-issued ID (passport, driver's license, PhilSys National ID, UMID, voter's ID, PRC ID, postal ID)",
          "Pag-IBIG Member's Data Form (MDF) — available at Pag-IBIG branches or downloadable from pagibigfund.gov.ph",
          "PSA-issued birth certificate (for verification of personal info)",
          "For employed: employer's Pag-IBIG Employer ID number",
          "TIN (Tax Identification Number)",
          "Active email address and mobile number (for online registration)",
        ],
        steps: [
          "Step 1 (Online): Go to pagibigfundservices.com/OnlineMembershipRegistration",
          "Step 2: Fill out the online registration form with personal details — full name, birthdate, address, contact info, TIN, and SSS number",
          "Step 3: Ensure your name and birthdate match your PSA birth certificate exactly",
          "Step 4: Submit the form. You will receive a Registration Tracking Number (RTN) — save this immediately",
          "Step 5: Your permanent Pag-IBIG MID (Membership ID) number will be available after a few days",
          "Step 6: Create your Virtual Pag-IBIG account at pagibigfundservices.com/virtualpagibig to track contributions, apply for loans, and enroll in MP2",
          "Alternative (walk-in): Visit the nearest Pag-IBIG branch, get or bring a pre-filled MDF form, submit with a photocopy of one valid ID, and receive your RTN on the spot",
          "If employed: Your employer handles mandatory registration and payroll deductions. Provide your MID number to HR",
        ],
        fees: "Free — Pag-IBIG registration has no fees",
        processingTime: "RTN: same day (online or walk-in). Permanent MID number: 3-5 business days",
        tips: [
          "Anyone aged 18-65 can register — even students, unemployed individuals, or OFWs",
          "Monthly contribution is 2% of salary (employer matches 2%). Maximum compensation for contribution is ₱10,000, so max contribution is ₱200/month each",
          "After 24 months of contributions, you become eligible for Pag-IBIG housing loans (up to ₱6,000,000)",
          "The MP2 savings program earns 6-7% annual dividends, tax-free — one of the best risk-free returns in the Philippines",
          "Multi-purpose loans (up to 80% of total Pag-IBIG savings) are available after 24 monthly contributions",
          "Set up your Virtual Pag-IBIG account immediately — it's the easiest way to monitor everything",
          "Keep your RTN and MID number saved on your phone for quick reference",
        ],
        references: [
          { label: "Pag-IBIG Fund Official Website", url: "https://www.pagibigfund.gov.ph/" },
          { label: "Pag-IBIG Online Registration", url: "https://www.pagibigfundservices.com/OnlineMembershipRegistration" },
          { label: "Virtual Pag-IBIG Portal", url: "https://www.pagibigfundservices.com/virtualpagibig/" },
        ],
      },
      {
        id: "philsys",
        title: "Get your PhilSys National ID",
        description: "The Philippine Identification System (PhilSys) card is the government's official national ID, designed to replace the need for multiple IDs.",
        why: "Once fully rolled out, it will be universally accepted for all government and private transactions. It's free, biometric-linked, and shows your PhilSys Number (PSN) — your permanent identity number.",
        how: "Schedule a Step 2 registration at philsys.gov.ph or walk in to a PSA registration center. Bring your birth certificate and proof of address. The card is mailed to your registered address.",
        priority: "critical",
        requirements: [
          "PSA-issued Certificate of Live Birth (original)",
          "One (1) government-issued ID with photo (passport, UMID, driver's license, voter's ID, PRC ID, postal ID)",
          "If no primary ID: two (2) secondary IDs (school ID, employee ID, barangay certificate/clearance, NBI clearance)",
          "Proof of address (utility bill, barangay certificate, or lease contract)",
          "For married applicants: PSA marriage certificate",
          "Application Reference Number (ARN) from online pre-registration",
        ],
        steps: [
          "Step 1 (Online Pre-Registration): Go to register.philsys.gov.ph and fill out the demographic information form",
          "Step 2: Provide your full name, birthdate, address, contact details, and other personal information",
          "Step 3: Save your Application Reference Number (ARN) and/or QR code — you will need this at the registration center",
          "Step 4: Choose your preferred PhilSys registration center and schedule an appointment date and time",
          "Step 5 (In-Person): On your appointment date, go to the selected registration center with your ARN/QR code and required documents",
          "Step 6: Present your documents for verification at the validation counter",
          "Step 7: Undergo biometric data capture — fingerprinting (all 10 fingers), iris scan, and front-facing photograph",
          "Step 8: Receive your Transaction Reference Number (TRN) on a transaction slip — keep this safe",
          "Step 9: Wait for your PhilID card to be delivered to your registered address, or check availability of your ePhilID at the registration center",
          "Step 10: You can also get a printable ePhilID (digital version) which is equally valid for transactions",
        ],
        fees: "Free — first-time registration and card issuance have no fees. Replacement of lost/damaged card will have a fee",
        processingTime: "Registration: same day. PhilID card delivery: varies (currently 2-6 months depending on location and backlog). ePhilID may be available sooner",
        tips: [
          "The PhilSys National ID is accepted as a single valid ID for ALL government and private transactions — no need to present multiple IDs",
          "Your PhilSys Number (PSN) is permanent and assigned for life — it cannot be changed",
          "The ePhilID (digital/printable version) is equally valid as the physical card for transactions",
          "Walk-in registration is available at some centers, but appointments are strongly recommended to avoid long waits",
          "If you registered online but haven't completed Step 2 (biometrics), visit any PhilSys registration center with your ARN",
          "Keep your TRN — you can use it to track your card delivery status",
          "The National ID replaces the need for NBI clearance, police clearance, or barangay certificate for identity verification purposes",
        ],
        references: [
          { label: "PhilSys Official Website", url: "https://philsys.gov.ph/" },
          { label: "PhilSys Online Registration", url: "https://register.philsys.gov.ph/" },
          { label: "PhilSys Registration Process", url: "https://philsys.gov.ph/registration-process/" },
          { label: "PhilSys FAQ", url: "https://philsys.gov.ph/faq-frequently-asked-questions/" },
        ],
      },
      {
        id: "umid",
        title: "Apply for your UMID Card",
        description: "The Unified Multi-Purpose ID combines your SSS, PhilHealth, Pag-IBIG, and GSIS membership into one card accepted everywhere.",
        why: "The UMID is one of the most widely accepted government IDs in the Philippines — banks, offices, even airports. It also functions as an ATM card for SSS benefits and loans.",
        how: "Apply at any SSS branch with at least one posted SSS contribution. Fill out the UMID card application form, provide biometrics (photo, fingerprint, signature). Processing takes about 4–8 weeks.",
        priority: "important",
        requirements: [
          "Active SSS membership with at least one (1) posted contribution",
          "One (1) primary valid ID (passport, driver's license, PRC ID, PhilSys National ID) — must be original, not photocopy",
          "If no primary ID: two (2) secondary valid IDs (voter's ID, postal ID, barangay certificate with photo, school ID, company ID)",
          "Fully accomplished UMID application form (available at SSS branches)",
          "Personal appearance required for biometric capture",
        ],
        steps: [
          "Step 1: Verify that you have at least one posted SSS contribution by logging into My.SSS at member.sss.gov.ph",
          "Step 2: Set an appointment with your preferred SSS branch using the Appointment System in the My.SSS Member Portal (recommended to avoid long queues)",
          "Step 3: Alternatively, walk in to any SSS branch following the number coding system (check the SSS website for the schedule)",
          "Step 4: Get and fill out the UMID application form at the SSS branch",
          "Step 5: Submit the form and your valid ID(s) at the receiving counter for document verification",
          "Step 6: Proceed to the enrolling station for biometric capture — photo, signature, and fingerprints",
          "Step 7: Receive an acknowledgment receipt — keep this safe as proof of your application",
          "Step 8: Wait for SMS or email notification that your UMID card is ready for pickup (4-6 weeks typically)",
          "Step 9: Claim your UMID card at the same SSS branch where you applied, or at the branch indicated in the notification",
        ],
        fees: "Free for first-time applicants. ₱200 replacement fee for lost, stolen, or damaged UMID cards",
        processingTime: "4-6 weeks from application. You will receive a notification (SMS/email) when the card is ready for pickup",
        tips: [
          "The UMID is one of the most widely accepted government IDs in the Philippines — accepted by banks, government agencies, airports, and private institutions",
          "The UMID card also functions as an ATM card for receiving SSS benefits and loan proceeds",
          "Note: SSS has been transitioning to the MySSS Card (formerly UMID). Check with your SSS branch for the latest card type being issued",
          "Set an appointment online to avoid very long walk-in queues, especially at Metro Manila branches",
          "Make sure your SSS records (name, birthdate, address) are updated and match your valid ID before applying",
          "Bring your original IDs — photocopies are not accepted for UMID applications",
          "If your UMID is lost, report it immediately to SSS and apply for a replacement",
        ],
        references: [
          { label: "SSS Official Website", url: "https://www.sss.gov.ph/" },
          { label: "My.SSS Portal", url: "https://member.sss.gov.ph/" },
          { label: "SSS UMID Card Guidelines", url: "https://www.sss.gov.ph/" },
        ],
      },
      {
        id: "passport",
        title: "Get a Philippine Passport",
        description: "Your passport is the most universally accepted ID in the Philippines and the world — it's your key to international travel.",
        why: "Even if you don't plan to travel abroad soon, having a passport gives you the most powerful ID for banking, visa applications, and official transactions. Valid for 10 years (adults).",
        how: "Schedule an appointment at dfa.gov.ph/passport. Prepare: PSA birth certificate, valid government ID, accomplished application form. Processing is 12 business days (regular) or 6 days (expedited). Cost: ₱950 (regular) or ₱1,200 (expedited).",
        priority: "important",
        requirements: [
          "PSA-authenticated Certificate of Live Birth (original and photocopy) on security paper",
          "One (1) valid government-issued ID with photo (driver's license, UMID, PhilSys National ID, PRC ID, voter's ID)",
          "Confirmed DFA online appointment (walk-ins are NOT allowed except for emergencies)",
          "Printed appointment confirmation page or saved on your phone",
          "For late-registered birth certificates (registered less than 10 years ago): additional NBI Clearance and IDs that pre-date the late registration",
          "For married applicants: PSA marriage certificate",
          "Personal appearance required — no representatives allowed",
        ],
        steps: [
          "Step 1: Go to passport.gov.ph and create an account or log in",
          "Step 2: Click 'Schedule an Appointment' and choose between new application or renewal",
          "Step 3: Select your preferred DFA office (consular office or satellite office), date, and time slot",
          "Step 4: Choose processing type — Regular (₱950) or Expedited (₱1,200)",
          "Step 5: Pay the passport fee online via Bayad Center, 7-Eleven, GCash, Maya, or credit/debit card",
          "Step 6: Print or save your confirmed appointment page with the reference number and QR code",
          "Step 7: On your appointment date, arrive at least 30 minutes early at the DFA office",
          "Step 8: Present your appointment confirmation and requirements at the receiving window",
          "Step 9: Proceed to encoding — your personal details will be entered into the system",
          "Step 10: Biometric capture — photo, fingerprints, and digital signature",
          "Step 11: Review the printed data sheet for any errors before signing",
          "Step 12: Receive your claim stub indicating the release date",
          "Step 13: Pick up your passport on the indicated release date, or opt for courier delivery (additional fee)",
        ],
        fees: "₱950 (regular processing) or ₱1,200 (expedited processing). Courier delivery: additional ₱150-300 depending on location",
        processingTime: "Metro Manila: 10 working days (regular), 5 working days (expedited). Outside Metro Manila: 12 working days (regular), 7 working days (expedited). Foreign Service Posts: 4-6 weeks",
        tips: [
          "Appointments fill up fast — book at least 2-4 weeks in advance, especially during peak travel months (March-June, November-December)",
          "DFA releases new appointment slots every day at midnight — check early for the best dates",
          "Dress neatly and avoid wearing white or light-colored tops for your passport photo (the background is white)",
          "Remove earrings, eyeglasses, and colored contact lenses for the photo",
          "The passport is valid for 10 years for adults (18+) and 5 years for minors",
          "If your PSA birth certificate has errors, fix them at the PSA or Local Civil Registrar BEFORE your passport appointment",
          "Courtesy lane is available for senior citizens, PWDs, pregnant women, and solo parents — bring supporting documents",
          "Keep a scanned copy of your passport's data page on your phone and in cloud storage for emergencies",
        ],
        references: [
          { label: "DFA Passport Appointment System", url: "https://www.passport.gov.ph/" },
          { label: "DFA Passport Requirements (New Adult)", url: "https://consular.dfa.gov.ph/adult-new/" },
          { label: "DFA Passport FAQ", url: "https://consular.dfa.gov.ph/passport-faq/" },
        ],
      },
      {
        id: "drivers-license",
        title: "Get a Driver's License (LTO)",
        description: "A non-professional driver's license lets you legally drive a private vehicle and is a widely accepted government ID.",
        why: "Required by law to drive. Also one of the most accepted IDs for banking and government transactions. Valid for 5 years.",
        how: "Step 1: Get a Student Permit at LTO — bring PSA birth certificate, valid ID, medical certificate, and pass the written exam. Step 2: After holding a student permit, apply for a non-professional license with a practical driving test. Process at lto.gov.ph or any LTO office.",
        priority: "good-to-have",
        requirements: [
          "Must be at least 16 years old for Student Permit, 17 years old for Non-Professional License",
          "PSA-issued birth certificate (original and photocopy)",
          "One (1) valid government-issued ID (PhilSys National ID, passport, UMID, TIN card, voter's ID)",
          "Medical certificate from an LTO-accredited clinic (physical and drug test)",
          "Completion certificate for the 15-hour Theoretical Driving Course (TDC) from an LTO-accredited driving school",
          "Completion certificate for the Practical Driving Course (PDC) — required for non-professional license",
          "Student Permit held for at least 30 days (to apply for non-professional license)",
          "No unsettled traffic violations",
        ],
        steps: [
          "PHASE 1: STUDENT PERMIT",
          "Step 1: Get a medical certificate from an LTO-accredited medical clinic (usually located near LTO offices). Cost: ₱350-₱500",
          "Step 2: Complete the 15-hour Theoretical Driving Course (TDC) at an LTO-accredited driving school. You'll receive a TDC completion certificate",
          "Step 3: Visit your nearest LTO District/Licensing Office and get an Application for Permits and Licenses (APL) form",
          "Step 4: Fill out the APL form and submit with your requirements at the evaluation counter",
          "Step 5: Pay the student permit fee (approximately ₱317.63 — includes application, computer, and permit fees)",
          "Step 6: Have your photo and biometrics captured",
          "Step 7: Take the theoretical (written) exam — you must pass to receive your Student Permit",
          "Step 8: Receive your Student Permit (valid for 1 year)",
          "PHASE 2: NON-PROFESSIONAL LICENSE (after 30+ days with Student Permit)",
          "Step 9: Complete the Practical Driving Course (PDC) at an LTO-accredited driving school",
          "Step 10: Return to an LTO office with your Student Permit, PDC completion certificate, and other requirements",
          "Step 11: Fill out a new APL form for Non-Professional License",
          "Step 12: Take the practical driving test at the LTO office",
          "Step 13: If you pass, pay the license fee (approximately ₱585 + ₱67.63 computer fee)",
          "Step 14: Have your photo and biometrics captured for the license card",
          "Step 15: Receive your Non-Professional Driver's License",
        ],
        fees: "Student Permit: ~₱317.63 (application + computer + permit fees). Non-Professional License: ~₱652.63 (license + computer fees). Medical certificate: ₱350-₱500. TDC: ₱2,000-₱4,000. PDC: ₱3,000-₱8,000. Total estimated cost: ₱6,000-₱13,000+",
        processingTime: "Student Permit: same day (if you pass the exam). Non-Professional License: same day (if you pass the driving test). Minimum 30 days must pass between getting Student Permit and applying for license",
        tips: [
          "Complete TDC and medical exam BEFORE visiting LTO — you cannot apply without these",
          "Schedule your LTO visit early in the morning (offices open at 8AM) to avoid long queues",
          "Some LTO offices have online appointment systems — check lto.gov.ph for availability",
          "Study for the theoretical exam using the LTO Reviewer app or practice exams online",
          "The practical driving test includes starting on an incline, parallel parking, and navigating an obstacle course",
          "Your non-professional license is valid for 5 years, with potential 10-year validity if you maintain a clean driving record",
          "You CANNOT drive alone with just a Student Permit — a licensed driver must accompany you at all times",
          "Keep your medical certificate fresh — it's only valid for 30 days from issuance for LTO purposes",
        ],
        references: [
          { label: "LTO Official Website", url: "https://lto.gov.ph/" },
          { label: "LTO Driver's License Guide", url: "https://ltoportal.org/drivers-license/" },
          { label: "LTO Student Permit Requirements", url: "https://ltoportal.org/lto-student-permit/" },
        ],
      },
      {
        id: "voters-id",
        title: "Register as a Voter (COMELEC)",
        description: "Voter registration gives you the right to vote in national and local elections — and your voter's certificate is accepted as a valid ID.",
        why: "Voting is your civic duty and your voice in shaping the Philippines. Local elections directly affect your community, schools, roads, and health services. Registration is free.",
        how: "Register at the COMELEC office in your municipality/city. Bring a valid ID and proof of residency. Online pre-registration is available at voterregistration.comelec.gov.ph. Registration periods open before every election.",
        priority: "important",
        requirements: [
          "Must be at least 18 years old on or before election day",
          "Must have resided in the Philippines for at least one (1) year and in the city/municipality where you intend to register for at least six (6) months before the election",
          "One (1) valid government-issued ID with photo (PhilSys National ID, SSS/GSIS/UMID, passport, driver's license, PRC ID, postal ID)",
          "Note: Cedulas (Community Tax Certificates), PNP clearance, and employee IDs are NOT accepted",
          "If no valid ID: a registered voter from your precinct or a relative within the 4th civil degree can identify you under oath",
          "Must not be disqualified from voting by law (e.g., convicted of a crime involving disloyalty to the government, insanity)",
        ],
        steps: [
          "Step 1: Check if voter registration is currently open — COMELEC opens registration periods before elections (check comelec.gov.ph for schedules)",
          "Step 2: Download the CEF-1 (Application for Registration) form from comelec.gov.ph, or get one at the Office of the Election Officer (OEO) in your city/municipality",
          "Step 3: Fill out the form completely — use black ink and print legibly. Include your full name, address, birthdate, and other personal details",
          "Step 4: Visit the OEO (COMELEC office) in the city/municipality where you intend to vote",
          "Step 5: Submit your accomplished CEF-1 form and present your valid ID",
          "Step 6: Have your biometrics captured — photo, fingerprints, and signature",
          "Step 7: Your application will be reviewed and included in the list of voters for your precinct",
          "Step 8: Check the COMELEC website or visit the OEO to confirm your registration was approved and to find your precinct assignment",
          "Step 9: On election day, bring your voter's ID or any valid ID to your assigned precinct to vote",
        ],
        fees: "Free — voter registration has no fees",
        processingTime: "Registration: same day (biometrics and application submission). Approval and precinct assignment: processed during the registration period. Voter's ID/certification: varies",
        tips: [
          "Registration periods are limited — don't wait until the last day. COMELEC typically opens registration 1-2 years before a national election",
          "If you've moved to a new city/municipality, you need to transfer your registration — file a transfer application at the OEO of your new residence",
          "You can check your voter registration status online at comelec.gov.ph using the Precinct Finder",
          "The Voter's ID is a valid government-issued ID accepted for many transactions",
          "Deactivated voters (those who failed to vote in two consecutive elections) must re-register",
          "Arrive early at the OEO — registration centers can get very crowded, especially near deadline dates",
          "Overseas Filipinos can register for overseas absentee voting at Philippine embassies or consulates",
        ],
        references: [
          { label: "COMELEC Official Website", url: "https://comelec.gov.ph/" },
          { label: "COMELEC Registration Requirements", url: "https://comelec.gov.ph/?r=VoterRegistration/WhatisVoterRegistration/RegistrationRequirements" },
          { label: "COMELEC How to Register", url: "https://comelec.gov.ph/?r=VoterRegistration/HowtoRegister" },
        ],
      },
      {
        id: "first-time-jobseeker",
        title: "Get your First Time Jobseeker Certificate",
        description: "A barangay certificate that exempts first-time job seekers from paying fees for government documents needed for employment.",
        why: "Republic Act 11261 (First Time Jobseekers Assistance Act) exempts you from paying documentary requirements for your first employment — including NBI clearance, police clearance, barangay clearance, and others. This saves you ₱500–₱1,500 in fees.",
        how: "Visit your Barangay Hall and request a First Time Jobseeker Certificate. Bring a valid ID and fill out the application form. The certificate is valid for 1 year from issuance.",
        priority: "critical",
        requirements: [
          "Any valid ID (school ID, birth certificate, voter's ID, or barangay ID)",
          "Filled-out oath of undertaking (provided at the barangay hall)",
          "Must be a resident of the barangay where you're applying",
          "Must be 18 years old and above",
          "Must not have been previously employed (this is for first-time job seekers only)",
        ],
        steps: [
          "Go to your Barangay Hall during office hours (usually 8 AM – 5 PM, Monday to Friday)",
          "Ask for the First Time Jobseeker Certificate application at the barangay secretary's office",
          "Fill out the application form and the Oath of Undertaking — this is your sworn statement that you're a first-time jobseeker",
          "Submit the form with a photocopy of your valid ID",
          "Wait for processing — usually takes 15-30 minutes",
          "Receive your certificate. Keep the original and make 3-4 photocopies",
          "Use the certificate when applying for: NBI Clearance (free), Police Clearance (free), Barangay Clearance (free), PSA Birth Certificate (free), and other employment requirements",
        ],
        fees: "Free — the certificate itself is free. It also exempts you from fees on other documents",
        processingTime: "Same day — usually 15-30 minutes",
        tips: [
          "Get this BEFORE applying for NBI clearance, police clearance, or any other employment documents — it exempts you from their fees",
          "The certificate is valid for 1 year. If you don't find a job within that period, you can renew it",
          "Make multiple photocopies — you'll need to present it at each government office where you claim exemption",
          "Some barangays may ask you to return the next day for signing by the barangay captain. Call ahead to check",
          "This only applies to your FIRST employment. Freelance work or online jobs may or may not count depending on the barangay's interpretation",
        ],
        references: [
          { label: "RA 11261 Full Text (First Time Jobseekers Act)", url: "https://www.officialgazette.gov.ph/2019/04/10/republic-act-no-11261/" },
        ],
      },
    ],
  },
  {
    id: "banking",
    number: 2,
    title: "Banking & Emergency Fund",
    subtitle: "Set up your financial infrastructure.",
    color: "text-emerald-600 dark:text-emerald-400",
    bg: "bg-emerald-500/10",
    borderColor: "border-emerald-500/30",
    items: [
      {
        id: "savings-account",
        title: "Open a bank savings account",
        description: "A traditional savings account at BDO, BPI, Metrobank, or UnionBank gives you access to ATMs nationwide, checks, and formal banking services.",
        why: "Cash under a mattress earns nothing and can be stolen. A savings account is the baseline for receiving payroll, paying bills, and accessing the financial system. Required for most loan applications.",
        how: "Visit any branch with two valid IDs and an initial deposit (BPI: ₱3,000; BDO: ₱2,000; UnionBank: ₱0). UnionBank's EON account and BDO's account can be opened fully online. Choose a bank near your home or office.",
        priority: "critical",
        appLink: "/accounts",
        appLinkLabel: "Track in Accounts",
        requirements: [
          "Two (2) valid government-issued IDs with photo (passport, driver's license, UMID, PhilSys National ID, PRC ID, voter's ID, postal ID)",
          "TIN (Tax Identification Number) — required by most banks even if unemployed",
          "Proof of billing address: latest utility bill (electricity, water, internet, phone) or credit card statement — must show your name and address",
          "Initial deposit amount (varies by bank: BPI ₱3,000, BDO ₱2,000, Metrobank ₱2,000, UnionBank ₱0 for EON, Security Bank ₱5,000-₱10,000)",
          "Active mobile number and email address",
          "For online account opening: smartphone with camera for selfie verification",
        ],
        steps: [
          "Step 1: Choose a bank based on branch proximity, ATM network, minimum balance requirements, and fees. Top choices for first-timers: BPI, BDO, UnionBank, or Metrobank",
          "Step 2 (In-Branch): Visit the nearest branch during banking hours (typically 9AM-3PM weekdays)",
          "Step 3: Get a queue number for 'New Accounts' and wait for your turn",
          "Step 4: Fill out the multi-page application form (Customer Information Sheet) — provide personal info, employment details, source of funds, and TIN",
          "Step 5: Submit the form with your two valid IDs. The bank officer will verify and photocopy your documents",
          "Step 6: The bank may ask clarifying questions about your employment, income source, and purpose of the account",
          "Step 7: Make your initial deposit at the cashier",
          "Step 8: Receive your passbook and/or ATM card (some banks issue ATM cards immediately, others mail them within 5-7 days)",
          "Step 9: Activate your online/mobile banking by downloading the bank's app and registering your account",
          "Alternative (Online): Banks like UnionBank (EON), BPI, and BDO allow fully online account opening — download the app, scan your ID, take a selfie, and fund via InstaPay",
        ],
        fees: "Account opening: Free. Maintaining balance varies (BPI: ₱3,000, BDO: ₱2,000, Metrobank: ₱10,000). Below-minimum balance fee: ₱300/month. ATM card replacement: ₱150-₱350. Some accounts have zero maintaining balance (e.g., UnionBank EON, BPI Save-Up)",
        processingTime: "In-branch: 30-60 minutes (same day). Online account opening: 5-15 minutes (may take 1-2 business days for full verification)",
        tips: [
          "Choose a bank with many ATMs near your home and office to avoid withdrawal fees (₱18-₱25 per transaction at other bank ATMs)",
          "UnionBank EON is excellent as a first account — zero maintaining balance, free online transfers, and fully online opening",
          "Always set up online/mobile banking immediately — it saves you from branch visits for transfers and bill payments",
          "Keep your maintaining balance above the minimum to avoid the ₱300/month penalty fee",
          "Set up your payroll to deposit directly into your bank account — ask HR for the bank enrollment form",
          "PDIC (Philippine Deposit Insurance Corporation) insures deposits up to ₱500,000 per depositor per bank",
          "Compare interest rates — most traditional banks offer only 0.10-0.25% p.a. on regular savings",
        ],
        references: [
          { label: "BPI Account Opening Requirements", url: "https://www.bpi.com.ph/personal/bank/list-of-account-opening-requirements" },
          { label: "BDO Personal Accounts", url: "https://www.bdo.com.ph/personal" },
          { label: "Security Bank Documents Needed", url: "https://www.securitybank.com/blog/documents-you-need-to-open-a-bank-account-in-the-philippines/" },
          { label: "PDIC Deposit Insurance", url: "https://www.pdic.gov.ph/" },
        ],
      },
      {
        id: "digital-savings",
        title: "Open a high-yield digital savings account",
        description: "ING (4% p.a.), CIMB (4.5% p.a.), and Maya (3.5% p.a.) offer savings rates far above traditional banks, with no maintaining balance.",
        why: "Traditional banks pay 0.10–0.25% interest. Digital banks pay 3–5%. On ₱50,000 in emergency funds, that's the difference between ₱125/year vs. ₱2,000/year — with zero maintaining balance.",
        how: "Download the app: ING Philippines, CIMB Bank, Maya, or Tonik. Sign up with a selfie + valid ID (passport or PhilSys). Account opens in minutes. Transfer money via InstaPay (₱50 fee, unless free with your sending bank).",
        priority: "important",
        appLink: "/accounts",
        appLinkLabel: "Track in Accounts",
        requirements: [
          "A smartphone (Android or iOS) with internet connection",
          "One (1) valid government-issued ID (PhilSys National ID, passport, driver's license, UMID, PRC ID, voter's ID, postal ID)",
          "Active mobile number (for OTP verification)",
          "Active email address",
          "Selfie for identity verification (taken in-app during registration)",
          "No minimum deposit required for most digital banks",
        ],
        steps: [
          "Step 1: Choose a digital bank based on interest rates and features. Top options: Maya Bank (up to 8% p.a. on Personal Goals), Tonik (up to 6% p.a. on time deposits), GoTyme (up to 5% p.a.), GCash/CIMB GSave (up to 4% p.a.)",
          "Step 2: Download the digital bank's app from Google Play Store or Apple App Store",
          "Step 3: Open the app and tap 'Sign Up' or 'Create Account'",
          "Step 4: Enter your mobile number and verify via OTP (one-time password)",
          "Step 5: Fill out personal details — full name, birthdate, address, email, source of funds",
          "Step 6: Upload or scan your valid government ID using your phone's camera",
          "Step 7: Take a selfie for identity verification — follow in-app instructions for proper lighting and angle",
          "Step 8: Review and submit your application",
          "Step 9: Wait for verification — most digital banks approve within minutes, some may take up to 24 hours",
          "Step 10: Once approved, you can start depositing via InstaPay, PESONet, or fund transfer from your existing bank account",
          "For GCash GSave: Open GCash app > tap 'Save Money' > GSave > 'Open a GSave Account' > follow prompts to create CIMB savings account within GCash",
        ],
        fees: "No account opening fee. No maintaining balance. No closing fee. Fund transfers via InstaPay: Free or ₱25-₱50 depending on the sending bank/app",
        processingTime: "Account opening: 5-15 minutes. Verification: instant to 24 hours. Account fully usable immediately upon approval",
        tips: [
          "Digital banks are regulated by the Bangko Sentral ng Pilipinas (BSP) and deposits are insured by PDIC up to ₱1,000,000 per depositor per bank — your money is safe",
          "Use digital bank accounts for your emergency fund — higher interest rates mean your money grows faster",
          "Maya Bank's Personal Goals feature lets you create up to 5 sub-accounts for different savings goals (e.g., emergency fund, travel, gadget)",
          "Interest rates change frequently — check the latest rates before opening. Promotional rates may be temporary",
          "You can link most digital bank accounts to e-wallets (GCash, Maya) for easy transfers",
          "Don't put all your money in one digital bank — spread across 2-3 to maximize PDIC insurance coverage and take advantage of different promo rates",
          "Set up auto-transfer from your payroll bank to your digital savings — automate the habit of saving",
        ],
        references: [
          { label: "Maya Bank Savings", url: "https://www.mayabank.ph/savings/" },
          { label: "Tonik Digital Bank", url: "https://tonik.com/" },
          { label: "GoTyme Bank", url: "https://www.gotyme.com.ph/" },
          { label: "BSP List of Digital Banks", url: "https://www.bsp.gov.ph/Pages/InclusiveFinance/DigitalBanks.aspx" },
        ],
      },
      {
        id: "emergency-fund-3mo",
        title: "Save 3 months of living expenses",
        description: "Your emergency fund covers job loss, medical emergencies, car repairs, or any unexpected expense — without going into debt.",
        why: "Without an emergency fund, any unexpected expense forces you to borrow (credit card, 5-6 loan). The average Filipino salary takes 3–6 months to find a new job. Your emergency fund is your self-insurance.",
        how: "Calculate your monthly expenses (rent + food + transport + utilities + insurance). Multiply by 3. Keep this in a separate high-yield savings account — don't mix it with your spending money. Automate a monthly transfer.",
        priority: "critical",
        appLink: "/goals",
        appLinkLabel: "Set Goal",
        requirements: [
          "A clear list of your essential monthly expenses (rent, food, transportation, utilities, insurance premiums, loan payments)",
          "A separate savings account dedicated ONLY to your emergency fund (preferably a high-yield digital bank)",
          "A commitment to consistent monthly savings — even small amounts count",
          "Knowledge of your monthly take-home pay (net salary after deductions)",
        ],
        steps: [
          "Step 1: List all your essential monthly expenses — rent/housing, food/groceries, transportation, utilities (electricity, water, internet, phone), insurance premiums, loan payments, and any other non-negotiable costs",
          "Step 2: Add them up to get your total monthly essential expenses. Example: ₱8,000 rent + ₱6,000 food + ₱3,000 transport + ₱2,000 utilities + ₱1,000 insurance = ₱20,000/month",
          "Step 3: Multiply by 3 to get your 3-month emergency fund target. Example: ₱20,000 x 3 = ₱60,000",
          "Step 4: Open a separate high-yield digital savings account (Maya, Tonik, GoTyme) exclusively for your emergency fund — do NOT mix it with your spending money",
          "Step 5: Determine how much you can save per month. Use the 50-30-20 rule: 50% needs, 30% savings, 20% wants. If that's too aggressive, start with 10-20% of your income",
          "Step 6: Break down your target into monthly chunks. Example: ₱60,000 target ÷ 12 months = ₱5,000/month. If that's too much, extend the timeline — even ₱2,000/month gets you there in 30 months",
          "Step 7: Automate your savings — set up an auto-transfer from your payroll bank to your emergency fund account on payday",
          "Step 8: Track your progress monthly. Celebrate milestones (₱10,000, ₱30,000, goal reached!)",
          "Step 9: Once you reach 3 months, keep going to 6 months for full financial security",
          "Step 10: If you ever use your emergency fund, prioritize replenishing it immediately",
        ],
        fees: "Free — no fees to save money. High-yield digital bank accounts have no maintaining balance or account fees",
        processingTime: "Depends on your income and savings rate. At ₱5,000/month savings: ~12 months for a ₱60,000 target. At ₱2,000/month: ~30 months. Start today regardless of the amount",
        tips: [
          "Start with whatever you can — even ₱50 or ₱100 a day adds up to ₱1,500-₱3,000 a month",
          "The emergency fund is NOT for wants — it's strictly for genuine emergencies: job loss, medical bills, car breakdown, home repairs",
          "Keep it in a liquid, accessible account — NOT in time deposits, stocks, or investments you can't withdraw instantly",
          "In the Filipino context, family obligations are real. Budget for them, but don't let them derail your emergency fund completely",
          "Cut unnecessary expenses to boost savings: cook at home instead of food delivery, cancel unused subscriptions, carpool instead of ride-hailing apps",
          "Use the 'pay yourself first' method — transfer savings BEFORE you start spending, not after",
          "Don't be discouraged by slow progress — a partial emergency fund is infinitely better than none",
          "Consider the ipon (saving) challenge: save ₱50 on week 1, ₱100 on week 2, ₱150 on week 3, etc. By week 52, you'll have over ₱68,000",
        ],
        references: [
          { label: "How to Build an Emergency Fund (MoneyMax)", url: "https://www.moneymax.ph/personal-finance/articles/start-emergency-fund" },
          { label: "Emergency Fund Guide for Filipinos (Maya)", url: "https://www.maya.ph/stories/5-best-practices-for-building-an-emergency-fund-a-guide-for-filipinos" },
          { label: "Emergency Fund Philippines (FinMerkado)", url: "https://www.finmerkado.ph/post/emergency-fund-philippines-high-interest-savings" },
        ],
      },
      {
        id: "understand-payslip",
        title: "Understand your payslip deductions",
        description: "Know exactly what SSS, PhilHealth, Pag-IBIG, and withholding tax amounts are being deducted from your salary every month.",
        why: "Many Filipinos don't know what they're actually earning vs. what's being withheld. Understanding deductions lets you verify your contributions are correct and plan your net take-home budget accurately.",
        how: "Check your payslip monthly. Verify SSS, PhilHealth, and Pag-IBIG amounts match the official tables. Withholding tax depends on your salary bracket. Use Sandalan's Contribution Calculator to verify your employer is computing correctly.",
        priority: "critical",
        appLink: "/tools/contributions",
        appLinkLabel: "Calculate Deductions",
        requirements: [
          "Your latest payslip (printed or digital — ask HR if you don't receive one regularly)",
          "Access to the SSS contribution table (2025: 15% total contribution rate, employee share varies by salary bracket)",
          "Access to the PhilHealth premium table (2025: 5% of monthly basic salary, split equally between employer and employee)",
          "Knowledge of Pag-IBIG contribution rates (2% of monthly salary, max ₱200/month for employee)",
          "BIR Withholding Tax Table (TRAIN Law graduated rates)",
        ],
        steps: [
          "Step 1: Get your payslip — request it from HR/payroll if you don't automatically receive one. You have a legal right to a payslip under DOLE regulations",
          "Step 2: Identify your Gross Salary — this is your total salary before any deductions",
          "Step 3: Check SSS deduction — for 2025, the total contribution rate is 15% (employee share varies). Use the SSS contribution table to verify your deduction matches your Monthly Salary Credit (MSC). MSC ranges from ₱5,000 to ₱35,000",
          "Step 4: Check PhilHealth deduction — the premium rate is 5% of your monthly basic salary, split 50/50 with your employer. Your share is 2.5%. Minimum: ₱250/month (your share). Maximum: ₱2,500/month (for salaries ₱100,000+)",
          "Step 5: Check Pag-IBIG deduction — your employee share is 2% of monthly salary (max compensation basis is ₱10,000, so max deduction is ₱200/month). Your employer matches this amount",
          "Step 6: Check Withholding Tax — subtract SSS + PhilHealth + Pag-IBIG from your gross salary to get taxable income. Under the TRAIN Law: income up to ₱20,833/month (₱250,000/year) is tax-exempt. Above that, graduated rates apply (20-35%)",
          "Step 7: Verify Net Pay — Gross Salary minus (SSS + PhilHealth + Pag-IBIG + Withholding Tax + any voluntary deductions like loans) = your take-home pay",
          "Step 8: Compare your computed amounts with what's on your payslip. If there are discrepancies, bring it up with HR/payroll immediately",
          "Step 9: Check your SSS, PhilHealth, and Pag-IBIG portals to confirm your employer is actually remitting the deducted amounts",
        ],
        fees: "N/A — these are mandatory deductions, not fees. Your total mandatory deductions typically range from 8-15% of your gross salary depending on your bracket",
        processingTime: "N/A — payslip review should be done every payday (semi-monthly or monthly)",
        tips: [
          "Your employer is LEGALLY REQUIRED to give you a payslip. If they refuse, report it to DOLE",
          "Use online calculators like taxcalculatorphilippines.com or sweldongpinoy.com to double-check your deductions",
          "Under the TRAIN Law (2018), if you earn ₱250,000 or below annually (about ₱20,833/month), you are EXEMPT from income tax",
          "Overtime pay, holiday pay, night shift differential, and hazard pay are computed separately and have different tax treatments",
          "13th month pay and other benefits up to ₱90,000 combined are tax-exempt",
          "If your employer deducts contributions but doesn't remit them to SSS/PhilHealth/Pag-IBIG, this is illegal. Check your contribution portals regularly",
          "Keep all your payslips — they serve as proof of income for loan applications, credit cards, and future employment",
          "Your BIR Form 2316 (issued every January) summarizes your annual income and taxes — cross-reference it with your total payslip deductions for the year",
        ],
        references: [
          { label: "SSS 2025 Contribution Table", url: "https://www.sss.gov.ph/contribution/" },
          { label: "PhilHealth Premium Contributions", url: "https://www.philhealth.gov.ph/" },
          { label: "Pag-IBIG Contribution Table", url: "https://www.pagibigfund.gov.ph/Membership.html" },
          { label: "BIR Withholding Tax Table (TRAIN Law)", url: "https://www.bir.gov.ph/tax-information/withholding-tax" },
          { label: "Sweldong Pinoy Tax Calculator", url: "https://www.sweldongpinoy.com/" },
        ],
      },
      {
        id: "credit-card",
        title: "Get a credit card (responsibly)",
        description: "A credit card builds your credit history, earns rewards/cashback, and provides a safety net — only if you pay the full balance every month.",
        why: "Credit cards are a tool, not free money. Paying in full every month costs you nothing (0% effective rate) and earns rewards. Minimum payments trap you in 24–36% annual interest — the single worst financial mistake Filipinos make.",
        how: "Apply at BPI (Amore), BDO (Visa Classic), or Security Bank (Complete Cashback). Requirements: Certificate of Employment, 2 months payslips, TIN, and 1 valid ID. Start with a low limit. Golden rule: never charge what you can't pay by billing date.",
        priority: "good-to-have",
        requirements: [
          "Must be 21-65 years old (some banks accept 18+ with a co-signer)",
          "Filipino citizen or foreign national residing in the Philippines for at least 2 years",
          "Minimum gross annual income of ₱120,000-₱252,000 (varies by bank and card type — some starter cards accept lower income)",
          "At least 1 year of regular employment or 1-2 years of profitable business/freelance work",
          "Two (2) valid government-issued IDs with photo (passport, driver's license, UMID, PhilSys National ID)",
          "TIN (Tax Identification Number)",
          "Certificate of Employment (COE) with compensation — request from HR",
          "Latest 2-3 months payslips or ITR (Income Tax Return) for self-employed",
          "Proof of billing address (latest utility bill or credit card statement)",
        ],
        steps: [
          "Step 1: Check if you meet the minimum income requirement — most basic cards require ₱120,000-₱180,000 gross annual income (₱10,000-₱15,000/month)",
          "Step 2: Research starter-friendly credit cards. Top picks for first-timers: PNB Ze-Lo Mastercard (no annual fee, low income requirement), BPI Amore Cashback, RCBC Classic Mastercard, Security Bank Complete Cashback",
          "Step 3: Apply online through the bank's website (most convenient) or visit a branch. Online applications: go to the bank's official website and look for 'Apply for Credit Card'",
          "Step 4: Fill out the application form — provide personal details, employment info, income, and existing bank accounts",
          "Step 5: Upload or submit required documents: valid IDs, COE with salary, latest payslips, proof of billing address",
          "Step 6: Wait for the bank's evaluation and credit check (they may call your employer or references to verify)",
          "Step 7: If approved, your credit card will be delivered to your billing address within 7-14 business days",
          "Step 8: Activate your card by calling the activation hotline or through the bank's mobile app",
          "Step 9: Set up your online banking to monitor transactions and pay your balance",
          "Step 10: Start with small purchases and ALWAYS pay the full balance before the due date",
        ],
        fees: "Annual fee: ₱0-₱2,500 depending on the card (some starter cards have no annual fee or waive it for the first year). Late payment fee: ₱500-₱850. Interest rate on unpaid balance: 2-3.5% per month (24-42% per year). Over-limit fee: ₱500. Cash advance fee: ₱200-₱500 + interest from day 1",
        processingTime: "Application evaluation: 7-14 business days. Card delivery (if approved): 5-10 business days after approval. Total: about 2-4 weeks from application to card in hand",
        tips: [
          "GOLDEN RULE: Pay your FULL balance every month by the due date — this means you pay ZERO interest. Only paying the minimum traps you in 24-42% annual interest",
          "Start with a low credit limit (₱10,000-₱30,000) until you develop discipline",
          "Use your credit card for regular expenses you'd buy anyway (groceries, gas, bills) to earn rewards — then pay it off in full",
          "NEVER use credit card cash advance — it charges interest from day 1 with no grace period, plus a transaction fee",
          "Set up auto-pay for the full statement balance to never miss a due date",
          "Keep your credit utilization below 30% of your limit (e.g., don't charge more than ₱9,000 on a ₱30,000 limit)",
          "If you're denied, try secured credit cards (backed by a bank deposit) as a stepping stone — RCBC and BPI offer these",
          "Having an existing savings/checking account with a bank significantly increases your approval chances for their credit card",
          "Never share your credit card number, CVV, or OTP with anyone — banks will NEVER ask for these via call, text, or email",
        ],
        references: [
          { label: "MoneyMax Credit Cards for First-Timers", url: "https://www.moneymax.ph/credit-card/articles/credit-cards-for-first-timers" },
          { label: "How to Apply for Your First Credit Card (MoneyMax)", url: "https://www.moneymax.ph/credit-card/articles/first-credit-card-guide" },
          { label: "BSP Consumer Protection", url: "https://www.bsp.gov.ph/Pages/ConsumerProtection/ConsumerProtection.aspx" },
        ],
      },
    ],
  },
  {
    id: "contributions",
    number: 3,
    title: "Government Contributions",
    subtitle: "Protect your future self — these are mandatory benefits, not just taxes.",
    color: "text-violet-600 dark:text-violet-400",
    bg: "bg-violet-500/10",
    borderColor: "border-violet-500/30",
    items: [
      {
        id: "sss-active",
        title: "Verify your SSS contributions are current",
        description: "Check your SSS contribution history to make sure your employer is remitting your deductions and that your records are accurate.",
        why: "Some employers deduct SSS but fail to remit — leaving you with gaps in your contribution history that affect your loan eligibility and eventual pension. You are entitled to sue your employer for this.",
        how: "Log in to my.sss.gov.ph → Contributions. Verify each month shows up. If a month is missing and you were employed, file a complaint with SSS. Keep payslip records as proof of your deductions.",
        priority: "critical",
        appLink: "/tools/contributions",
        appLinkLabel: "Track Contributions",
        requirements: [
          "Your SSS number (SS number)",
          "A registered My.SSS account at member.sss.gov.ph (if you don't have one, register first)",
          "Your My.SSS login credentials (user ID and password)",
          "A computer, tablet, or smartphone with internet access",
          "Your payslips as reference to cross-check deductions vs. actual remittances",
        ],
        steps: [
          "Step 1: Go to member.sss.gov.ph and log in with your My.SSS user ID and password",
          "Step 2: On the dashboard, hover over or click 'E-Services' in the menu bar",
          "Step 3: In the dropdown menu, select 'Inquiry' then 'Contributions'",
          "Step 4: Your contribution history will display — it shows each month's contribution amount, the employer who remitted, and the posting date",
          "Step 5: Cross-reference with your payslips — for every month you were employed and had SSS deductions, there should be a corresponding entry",
          "Step 6: If a month is MISSING, it means your employer deducted but did not remit — this is illegal",
          "Step 7: To check employment history: go to E-Services > Inquiry > Employment History to see all employers who reported you",
          "Step 8: If you find discrepancies, file a formal complaint with SSS — bring your payslips as evidence",
          "Alternative: Download the SSS Mobile App (available on Google Play and App Store) and log in with your My.SSS credentials to check on the go",
        ],
        fees: "Free — checking contributions online has no fees",
        processingTime: "Instant — contribution records are available immediately upon login. Note: new contributions may take 3-5 working days to post after payment/remittance",
        tips: [
          "Check your contributions at least quarterly — don't wait until you need to file a claim to find out your employer hasn't been remitting",
          "Contributions may take 3-5 working days to appear after your employer remits, so don't panic if the latest month isn't showing yet",
          "Screenshot or download your contribution records periodically as backup documentation",
          "If your employer is not remitting, file a complaint at the nearest SSS branch — employers who don't remit face criminal penalties under RA 11199 (Social Security Act of 2018)",
          "Voluntary members: you can check if your personal payments were posted correctly using the same process",
          "Your total contributions determine your loan eligibility (salary loan requires 36 monthly contributions) and eventual pension amount",
          "If you forgot your My.SSS password, use the 'Forgot Password' feature — you'll need your SS number and registered email",
        ],
        references: [
          { label: "My.SSS Member Portal", url: "https://member.sss.gov.ph/" },
          { label: "SSS Mobile App", url: "https://www.sss.gov.ph/download-the-sss-mobile-app-2/" },
          { label: "SSS Official Website", url: "https://www.sss.gov.ph/" },
          { label: "SSS Hotline", url: "https://www.sss.gov.ph/contact-us/" },
        ],
      },
      {
        id: "philhealth-active",
        title: "Verify your PhilHealth contributions are current",
        description: "Check that your employer is remitting your PhilHealth contributions and that your membership is active for hospitalization benefits.",
        why: "If contributions aren't posted, you won't be able to use PhilHealth benefits when hospitalized. Members without active contributions may need to pay a differential fee to avail coverage.",
        how: "Log in to PhilHealth member portal at philhealth.gov.ph → Contributions. Check for gaps. Your employer should give you an MDR (Member Data Record) confirming active status. For outpatient: present PhilHealth ID and MDR at accredited facilities.",
        priority: "critical",
        appLink: "/tools/contributions",
        appLinkLabel: "Track Contributions",
        requirements: [
          "Your PhilHealth Identification Number (PIN)",
          "A registered PhilHealth Member Portal account at memberinquiry.philhealth.gov.ph",
          "Login credentials (PhilHealth number and password)",
          "A computer, tablet, or smartphone with internet access",
          "Your payslips for cross-referencing employer deductions",
        ],
        steps: [
          "Step 1: Go to memberinquiry.philhealth.gov.ph and log in with your PhilHealth number and password",
          "Step 2: If you don't have an account yet, click 'Register' and follow the prompts using your PIN, personal details, and valid email",
          "Step 3: Once logged in, navigate to the Contributions section to view your posted contribution history",
          "Step 4: Verify that each month shows a contribution — especially if you were employed during that period",
          "Step 5: Check your membership status — it should show 'Active' for you to be eligible for hospitalization benefits",
          "Step 6: Cross-reference contributions with your payslip deductions to ensure your employer is remitting correctly",
          "Step 7: If contributions are missing, request your MDR (Member Data Record) from your employer or from a PhilHealth LHIO office",
          "Step 8: Report any discrepancies to PhilHealth by visiting the nearest LHIO or emailing actioncenter@philhealth.gov.ph",
          "Alternative: Email actioncenter@philhealth.gov.ph with your complete name, birthdate, and a photo of your valid ID to request a membership status check",
        ],
        fees: "Free — checking PhilHealth status online has no fees",
        processingTime: "Instant — records are available upon login. New contributions may take several weeks to post after employer remittance",
        tips: [
          "PhilHealth contributions take longer to post compared to SSS — don't panic if the latest months aren't showing yet, but do follow up if it's been more than 2 months",
          "Your employer is required to issue your MDR (Member Data Record) — this is your proof of active membership for hospital admissions",
          "Under the Universal Health Care (UHC) Law, all Filipinos are eligible for PhilHealth benefits, but having active contribution status ensures full benefit coverage",
          "Always present your PhilHealth ID or PhilSys National ID (linked to PhilHealth) at hospital admission — this triggers the automatic deduction of PhilHealth coverage from your bill",
          "If you're changing employers, ensure there's no gap in contributions — the new employer should start remitting immediately",
          "Voluntary members (freelancers, self-employed): you can pay contributions at any accredited payment center or through online banking",
          "Keep your Member Data Record (MDR) accessible — hospitals require this alongside your PhilHealth ID for benefit claims",
        ],
        references: [
          { label: "PhilHealth Member Portal", url: "https://memberinquiry.philhealth.gov.ph/member/" },
          { label: "PhilHealth Official Website", url: "https://www.philhealth.gov.ph/" },
          { label: "PhilHealth Online Services", url: "https://www.philhealth.gov.ph/services/" },
          { label: "PhilHealth Action Center Email", url: "mailto:actioncenter@philhealth.gov.ph" },
        ],
      },
      {
        id: "pagibig-active",
        title: "Verify your Pag-IBIG contributions are current",
        description: "Confirm monthly Pag-IBIG deductions are being remitted so your housing loan eligibility and MP2 savings are properly building.",
        why: "24 months of Pag-IBIG contributions makes you eligible for housing loans. If your employer isn't remitting, you lose eligibility and your contributions may not count.",
        how: "Log in at pagibig-fund.gov.ph → Virtual Pag-IBIG → Member's Contribution History. Or text PAG-IBIG <MID number> to 4643. Contact your HR if months are missing.",
        priority: "critical",
        appLink: "/tools/contributions",
        appLinkLabel: "Track Contributions",
        requirements: [
          "Your Pag-IBIG MID (Membership ID) number",
          "A registered Virtual Pag-IBIG account at pagibigfundservices.com/virtualpagibig",
          "Login credentials (registered email and password)",
          "A computer, tablet, or smartphone with internet access",
          "Your payslips for cross-referencing employer deductions",
        ],
        steps: [
          "Step 1: Go to pagibigfundservices.com/virtualpagibig and log in with your registered email and password",
          "Step 2: If you don't have an account, click 'Create Account' and register using your MID number, personal details, and email address",
          "Step 3: Once logged in, click the MENU icon (upper left on desktop, upper right on mobile)",
          "Step 4: Select 'Regular Savings' (Mandatory Contributions) from the menu",
          "Step 5: View your complete contribution history — it shows all contributions from your first remittance to the latest, including employee and employer shares",
          "Step 6: Check the total number of contributions, total employee share, total employer share, and accumulated dividends",
          "Step 7: Cross-reference with your payslips — every month your employer deducted Pag-IBIG should have a corresponding entry",
          "Step 8: If months are missing, contact your HR/payroll department immediately with your payslip evidence",
          "Step 9: To check MP2 savings (if enrolled): go back to the menu and select 'Modified Pag-IBIG II (MP2)' to see your MP2 contributions and dividends",
          "Alternative: Download the Virtual Pag-IBIG Mobile App from Google Play or App Store for checking on the go",
        ],
        fees: "Free — checking contributions online has no fees",
        processingTime: "Instant — contribution records are available upon login. New contributions may take a few weeks to post after employer remittance",
        tips: [
          "Check your contributions at least quarterly to catch any non-remittance early",
          "Your total Pag-IBIG savings (employee + employer shares + dividends) can be withdrawn upon retirement, disability, or after 20 years of continuous membership",
          "You need 24 months of contributions to be eligible for Pag-IBIG housing loans and multi-purpose loans",
          "The annual dividend rate has been consistently between 5-7% — much higher than regular bank savings",
          "Consider enrolling in MP2 (Modified Pag-IBIG II) for voluntary savings that earn the same high dividend rate, tax-free",
          "If your employer is not remitting, report to the nearest Pag-IBIG branch — penalties apply to non-compliant employers",
          "You can also check your loan balance and loan payment history through Virtual Pag-IBIG",
          "Download statements periodically — they serve as proof of savings for loan applications",
        ],
        references: [
          { label: "Virtual Pag-IBIG Portal", url: "https://www.pagibigfundservices.com/virtualpagibig/" },
          { label: "Virtual Pag-IBIG Mobile App", url: "https://play.google.com/store/apps/details?id=pagibigfund.virtualpagibigapp" },
          { label: "Pag-IBIG Fund Official Website", url: "https://www.pagibigfund.gov.ph/" },
        ],
      },
      {
        id: "13th-month",
        title: "Know your 13th month pay rights",
        description: "All rank-and-file employees are legally entitled to 13th month pay — at least 1/12 of your basic annual salary, paid on or before December 24.",
        why: "It's not a bonus — it's the law (Presidential Decree No. 851). Up to ₱90,000 is tax-exempt. Some employers try to include it in monthly salary ('already included') which is illegal. Know your rights.",
        how: "Formula: (Total Basic Salary Earned in a Year) ÷ 12. Compute yours in Sandalan. If you think you were underpaid, file a complaint with DOLE (Department of Labor and Employment). Must be paid regardless of resignation or separation.",
        priority: "critical",
        appLink: "/tools/thirteenth-month",
        appLinkLabel: "13th Month Calculator",
        requirements: [
          "Knowledge of your basic monthly salary (excluding overtime, holiday pay, night differential, and allowances unless stated in your contract)",
          "Your payslips for the year to verify total basic salary earned",
          "Employment contract (to check if additional pay components are included in basic salary computation)",
          "DOLE contact information in case of disputes",
        ],
        steps: [
          "Step 1: Understand the formula — 13th Month Pay = Total Basic Salary Earned During the Year ÷ 12",
          "Step 2: Identify your basic salary — this is your fixed monthly pay EXCLUDING overtime pay, holiday pay, night shift differential, and allowances (unless your contract says otherwise)",
          "Step 3: If you worked the full year (January-December) with a fixed salary, your 13th month pay equals one month's basic salary. Example: ₱25,000/month x 12 months = ₱300,000 ÷ 12 = ₱25,000",
          "Step 4: If you worked only part of the year (prorated): multiply your monthly salary by the number of months worked, then divide by 12. Example: Started in July, ₱25,000/month x 6 months = ₱150,000 ÷ 12 = ₱12,500",
          "Step 5: Check your payslip or ask HR when the 13th month pay will be released — it must be paid on or before December 24",
          "Step 6: Verify the amount received matches your computation. If it doesn't, request a breakdown from HR",
          "Step 7: If you believe you were underpaid or your employer refuses to pay, file a complaint with DOLE at the nearest regional office",
          "Step 8: Check the tax exemption — 13th month pay and other benefits up to ₱90,000 combined are tax-exempt. Amounts exceeding ₱90,000 are subject to income tax",
        ],
        fees: "N/A — 13th month pay is an employee benefit, not a cost. It is required by law under Presidential Decree No. 851",
        processingTime: "Must be paid by employer on or before December 24 of each year. Some employers pay half in June and the other half in December",
        tips: [
          "13th month pay is NOT a bonus — it's a mandatory benefit required by law. Your employer cannot skip it or 'include it' in your monthly salary",
          "ALL rank-and-file employees are entitled to 13th month pay regardless of position, employment status (regular, probationary, contractual), or method of pay (daily, weekly, monthly)",
          "You are entitled to 13th month pay even if you resign or are terminated — it will be prorated based on months worked",
          "Overtime pay, holiday pay, night shift differential, and hazard pay are NOT included in the computation — only basic salary",
          "Some generous employers give 14th or 15th month pay as a Christmas bonus — this is voluntary and separate from the mandatory 13th month",
          "If your employer fails to pay by December 24, no exemption or deferment is allowed. Report non-compliance to DOLE",
          "Managers and supervisors are NOT entitled to 13th month pay under the law, but many companies extend it as a company benefit",
          "The ₱90,000 tax exemption threshold covers 13th month pay PLUS all other benefits (Christmas bonus, productivity incentives, etc.) — only the excess is taxed",
        ],
        references: [
          { label: "DOLE 13th Month Pay Guidelines", url: "https://laborlaw.ph/13th-month-pay/" },
          { label: "Presidential Decree No. 851", url: "https://www.officialgazette.gov.ph/1975/12/16/presidential-decree-no-851-s-1975/" },
          { label: "DOLE Official Website", url: "https://www.dole.gov.ph/" },
          { label: "13th Month Pay Computation Guide", url: "https://everythingatwork.com/how-to-compute-13th-month-pay-in-the-philippines-2025-update/" },
        ],
      },
    ],
  },
  {
    id: "tax",
    number: 4,
    title: "Tax Compliance",
    subtitle: "File correctly, avoid penalties, and never pay more than you owe.",
    color: "text-orange-600 dark:text-orange-400",
    bg: "bg-orange-500/10",
    borderColor: "border-orange-500/30",
    items: [
      {
        id: "bir-2316",
        title: "Get your BIR Form 2316 from your employer",
        description: "Form 2316 is the Certificate of Compensation Payment and Tax Withheld — proof of your income and taxes paid, issued by your employer every January.",
        why: "This document proves your tax was withheld correctly. You need it for loan applications (housing, bank), new employer onboarding, and to verify your annual tax was properly settled. Never lose it.",
        how: "Ask HR or payroll every January for your 2316 covering the previous year. If your employer failed to issue one, they're violating the Tax Code. Scan it and keep a digital copy. Most employers issue it by January 31.",
        priority: "critical",
        appLink: "/tools/taxes",
        appLinkLabel: "BIR Tax Tracker",
      },
      {
        id: "substituted-filing",
        title: "Know if you need to file an ITR yourself",
        description: "Most pure employees with one employer qualify for Substituted Filing — meaning your employer files on your behalf and you don't need to file Form 1700.",
        why: "Filing when not required wastes time. NOT filing when required leads to penalties of 25% surcharge + 12% interest per year + ₱1,000 compromise penalty. Know your classification.",
        how: "You don't need to file if: single employer, compensation income only, tax was correctly withheld, employer files BIR Alphalist. You MUST file (Form 1700) if: two or more employers in a year, business income, compensation exceeds ₱2.4M, or you want a tax refund.",
        priority: "critical",
        appLink: "/tools/taxes",
        appLinkLabel: "BIR Tax Tracker",
      },
      {
        id: "bir-freelancer",
        title: "Register with BIR as freelancer or self-employed",
        description: "If you have any income outside of a formal employer — freelancing, consulting, online selling, or a side business — you must register with BIR.",
        why: "Unregistered businesses and freelancers face back taxes, 25% surcharge, 12% annual interest, and compromise penalties going back 3–10 years. The BIR has been actively running after digital earners and influencers.",
        how: "File BIR Form 1901 at your RDO with TIN, proof of business address, and valid ID. Register your books of accounts. Print Official Receipts (ORs) or use the eBIRForms system. Annual registration fee: ₱500. File quarterly (1701Q) and annual (1701/1701A) ITR.",
        priority: "critical",
        appLink: "/tools/taxes",
        appLinkLabel: "BIR Tax Tracker",
      },
      {
        id: "bir-deductions",
        title: "Know your allowable deductions",
        description: "Self-employed individuals can deduct business expenses OR choose the Optional Standard Deduction (OSD) of 40% of gross income — whichever lowers your tax more.",
        why: "Many self-employed Filipinos overpay because they don't know they can deduct internet, phone, home office, transportation, professional development, and health insurance premiums from their taxable income.",
        how: "Keep receipts for all business-related expenses. If expenses exceed 40% of income, itemize. If not, use OSD. Also consider the 8% flat income tax option if gross sales/receipts are below ₱3,000,000 — often simpler and lower than graduated rates.",
        priority: "important",
        appLink: "/tools/taxes",
        appLinkLabel: "BIR Tax Tracker",
      },
    ],
  },
  {
    id: "insurance",
    number: 5,
    title: "Insurance & Protection",
    subtitle: "Don't let one bad event wipe out everything you've built.",
    color: "text-teal-600 dark:text-teal-400",
    bg: "bg-teal-500/10",
    borderColor: "border-teal-500/30",
    items: [
      {
        id: "philhealth-benefits",
        title: "Learn how to actually use your PhilHealth",
        description: "Knowing how to use your PhilHealth benefits can save you tens of thousands of pesos during hospitalization — most members don't claim what they're entitled to.",
        why: "PhilHealth covers specific amounts per diagnosis (case rate) regardless of actual hospital bill. For normal delivery alone it covers ₱6,500. Without knowing how to file, you leave money on the table.",
        how: "Present PhilHealth ID + MDR at accredited hospital admission. The hospital files PhilHealth claims on your behalf. For outpatient: Z-benefits cover cancer, dialysis, and selected conditions. Check philhealth.gov.ph/services for the full benefits table.",
        priority: "critical",
        appLink: "/tools/insurance",
        appLinkLabel: "Insurance Tracker",
      },
      {
        id: "hmo",
        title: "Get HMO coverage",
        description: "An HMO (Health Maintenance Organization) covers outpatient consultations, diagnostics, and emergency room visits that PhilHealth doesn't fully cover.",
        why: "PhilHealth mostly covers inpatient care. A single ER visit, lab workup, or specialist consultation can cost ₱2,000–₱10,000 out of pocket. HMO fills this gap. Company HMO is free — always enroll in it if offered.",
        how: "If employed: enroll in your company's HMO during open enrollment — it's usually free or subsidized. If self-employed: personal plans from Maxicare, Medicard, or Intellicare start at ~₱3,000–₱8,000/year. Compare online at HMO comparison sites.",
        priority: "critical",
        appLink: "/tools/insurance",
        appLinkLabel: "Insurance Tracker",
      },
      {
        id: "life-insurance",
        title: "Get term life insurance",
        description: "Term life insurance pays your beneficiaries a lump sum if you die during the coverage period — pure protection with no investment component.",
        why: "If anyone depends on your income (parents, spouse, kids), you need life insurance. Rule of thumb: 10x your annual income in coverage. Term insurance is 3–5x cheaper than VUL for the same coverage. Most Filipinos are oversold VULs when term would serve them better.",
        how: "Get term insurance first: PRULife's PRUTerm One, Sun Life's SunTerm, or AXA's FlexiProtect. Annual premiums for ₱1,000,000 coverage start around ₱3,000–₱5,000/year for a healthy 25-year-old. Avoid mixing insurance with investment (VUL) until you fully understand both.",
        priority: "important",
        appLink: "/tools/insurance",
        appLinkLabel: "Insurance Tracker",
      },
      {
        id: "ctpl",
        title: "CTPL: Mandatory vehicle insurance",
        description: "Compulsory Third Party Liability (CTPL) insurance is required by law for all motor vehicle registrations at LTO. No CTPL = no LTO sticker.",
        why: "CTPL covers bodily injury or death to third parties in road accidents — not your own vehicle. It's the minimum legal requirement. Driving without valid LTO registration (which requires CTPL) is a criminal offense.",
        how: "Buy CTPL from any insurance company accredited by LTO: COCOGEN, Malayan, Charter Ping An, etc. 1-year coverage costs ~₱400–₱800. Purchase at LTO during registration renewal, at authorized payment centers, or online through Gcash/Maya.",
        priority: "important",
        appLink: "/tools/insurance",
        appLinkLabel: "Insurance Tracker",
      },
    ],
  },
  {
    id: "investing",
    number: 6,
    title: "Investing & Building Wealth",
    subtitle: "Make your money work — after your foundation is solid.",
    color: "text-amber-600 dark:text-amber-400",
    bg: "bg-amber-500/10",
    borderColor: "border-amber-500/30",
    items: [
      {
        id: "emergency-fund-6mo",
        title: "Build a full 6-month emergency fund",
        description: "Expand your emergency fund to cover 6 months of living expenses — especially if you're self-employed or in an industry with high job instability.",
        why: "3 months is the minimum. 6 months is the real target — especially for freelancers, commission-based workers, or those with dependents. This is the foundation; you should not invest until this is done.",
        how: "Calculate: monthly expenses × 6. Keep in a separate high-yield savings account (ING, CIMB). Don't invest this money — it must be liquid and immediately accessible. Top it up if you ever tap it.",
        priority: "critical",
        appLink: "/goals",
        appLinkLabel: "Set Goal",
      },
      {
        id: "mp2",
        title: "Start Pag-IBIG MP2 savings",
        description: "Modified Pag-IBIG II is a voluntary savings program that earns 6–7% annual dividends, fully tax-free — one of the best guaranteed returns in the Philippines.",
        why: "MP2 consistently outperforms most bank time deposits and UITFs with much lower risk. It's government-guaranteed. The 5-year maturity is flexible — you can withdraw dividends annually or let them compound.",
        how: "Log in to Virtual Pag-IBIG → MP2 Enrollment. Minimum: ₱500/month or lump sum ₱500. Set up auto-debit from your bank account. After 5 years, you can withdraw the entire principal + dividends or roll over for another 5 years.",
        priority: "important",
        appLink: "/goals",
        appLinkLabel: "Track Savings Goal",
      },
      {
        id: "uitf",
        title: "Open a UITF or mutual fund account",
        description: "Unit Investment Trust Funds (UITFs) pool money from many investors to invest in bonds, equities, or a mix — professionally managed with as little as ₱1,000.",
        why: "Higher long-term returns than savings accounts (equity UITFs historically return 8–12% annually). You can start small, invest regularly, and not need to pick individual stocks. Good for 5–10+ year goals.",
        how: "Open through your existing bank: BDO, BPI, or UnionBank UITFs can be started online. Choose based on risk: Money Market (lowest) → Bond → Balanced → Equity (highest). Start with ₱1,000. Read the Key Information Document (KID) before investing.",
        priority: "important",
        appLink: "/goals",
        appLinkLabel: "Track Investment Goal",
      },
      {
        id: "stocks-pse",
        title: "Learn about the Philippine Stock Exchange",
        description: "Investing in PSE-listed companies lets you own a piece of SM, Ayala, JG Summit, BDO, and others — with the potential for long-term wealth creation.",
        why: "The PSE has historically returned 8–12% annually over 10+ year periods. Dividends provide passive income. Owning blue-chip stocks is a proven long-term wealth strategy — but requires patience and a 10+ year mindset.",
        how: "Open an account with COL Financial (easiest for beginners), BDO Nomura, or First Metro Securities. Minimum: ₱1,000 with COL. Start with blue-chip stocks: SM, Ayala Land, BDO, BPI, Jollibee. Never invest money you need within 5 years.",
        priority: "good-to-have",
        appLink: "/goals",
        appLinkLabel: "Track Investment Goal",
      },
      {
        id: "sss-voluntary",
        title: "Make voluntary SSS contributions to increase your pension",
        description: "The maximum monthly SSS pension is tied to your Monthly Salary Credit (MSC). Higher contributions = higher pension. You can voluntarily contribute above the minimum.",
        why: "The default SSS pension for minimum-wage workers can be as low as ₱1,500–₱2,000/month — far below the poverty line. Increasing your MSC now dramatically increases your future retirement pension.",
        how: "Log in to my.sss.gov.ph → Payment Reference Number (PRN) → select voluntary contribution amount. You can contribute up to the maximum MSC of ₱30,000. Payments via GCash, online banking, or SSS-accredited payment centers.",
        priority: "good-to-have",
        appLink: "/tools/contributions",
        appLinkLabel: "Contributions Tracker",
      },
    ],
  },
  {
    id: "estate",
    number: 7,
    title: "Estate & Legacy Planning",
    subtitle: "Protect your family even when you're no longer there.",
    color: "text-slate-600 dark:text-slate-400",
    bg: "bg-slate-500/10",
    borderColor: "border-slate-500/30",
    items: [
      {
        id: "beneficiaries",
        title: "Update beneficiaries on all accounts",
        description: "Make sure your SSS, PhilHealth, Pag-IBIG, bank accounts, and insurance policies have updated and correct beneficiaries.",
        why: "Without designated beneficiaries, death benefits get tied up in lengthy legal proceedings. Courts, lawyers, and estate taxes can eat up to 20–30% of what you leave behind. A simple form update can save your family years of grief.",
        how: "SSS: Update E-4 form at any SSS branch. Pag-IBIG: Submit MDF (Membership Data Form) at a branch. Banks: Ask for beneficiary designation forms — most banks offer this. Insurance: Call your insurance provider or go to their office.",
        priority: "important",
      },
      {
        id: "will",
        title: "Create a basic last will and testament",
        description: "A notarized will ensures your assets go where you want them to, protects your family from succession disputes, and makes the estate settlement process faster.",
        why: "Without a will, Philippine intestate law distributes your estate according to the Civil Code — which may not match your wishes. Family disputes over inheritance are common and devastating. A will minimizes conflict.",
        how: "Hire a lawyer to draft a notarial will (most affordable: ₱3,000–₱8,000 with a notary). Alternatively, a holographic will (handwritten, dated, signed) is valid in the Philippines with no notarization needed. Keep the original in a safe place; give a copy to a trusted person.",
        priority: "good-to-have",
      },
      {
        id: "estate-tax",
        title: "Understand estate tax",
        description: "When you pass away, the Philippine government imposes a 6% estate tax on the net estate above ₱5,000,000 — paid before heirs can claim assets.",
        why: "Many Filipino families lose portions of their inheritance because they don't understand estate taxes or can't afford to pay them. Prior planning (insurance, proper titling, estate tax amnesty) can significantly reduce this burden.",
        how: "The estate tax return (BIR Form 1801) must be filed within 1 year of death. Consider estate tax insurance — a life insurance policy sized to cover anticipated estate taxes. Keep property titles, bank records, and key documents organized and accessible to heirs.",
        priority: "good-to-have",
      },
    ],
  },
];

export const ALL_ITEMS = CHECKLIST_PHASES.flatMap((p) => p.items);

export const TOTAL_ITEMS = ALL_ITEMS.length;

export const PRIORITY_META: Record<ChecklistPriority, { label: string; color: string; bg: string }> = {
  critical: { label: "Must Do", color: "text-red-600 dark:text-red-400", bg: "bg-red-500/10" },
  important: { label: "Should Do", color: "text-amber-600 dark:text-amber-400", bg: "bg-amber-500/10" },
  "good-to-have": { label: "Nice to Have", color: "text-blue-600 dark:text-blue-400", bg: "bg-blue-500/10" },
};
