export type ChecklistPriority = "critical" | "important" | "good-to-have";

export interface ChecklistItem {
  id: string;
  title: string;
  description: string;
  why: string;
  how: string;
  priority: ChecklistPriority;
  appLink?: string;
  appLinkLabel?: string;
}

export interface ChecklistPhase {
  id: string;
  number: number;
  title: string;
  subtitle: string;
  color: string;
  bg: string;
  borderColor: string;
  items: ChecklistItem[];
}

export const CHECKLIST_PHASES: ChecklistPhase[] = [
  {
    id: "government-ids",
    number: 1,
    title: "Government IDs & Registration",
    subtitle: "The documents you need before anything else.",
    color: "text-blue-600 dark:text-blue-400",
    bg: "bg-blue-500/10",
    borderColor: "border-blue-500/30",
    items: [
      {
        id: "tin",
        title: "Get your TIN from BIR",
        description: "Your Tax Identification Number is required for employment, banking, business registration, and almost every government transaction.",
        why: "You legally cannot be employed or open most bank accounts without a TIN. Having multiple TINs is a criminal offense with penalties up to ₱1,000 and/or imprisonment.",
        how: "If employed: your employer processes it via BIR Form 1902. If self-employed/freelancer: go to your local BIR Revenue District Office (RDO) with a valid ID and BIR Form 1901. Alternatively, use the BIR eRegistration portal at bir.gov.ph.",
        priority: "critical",
        appLink: "/adulting/taxes",
        appLinkLabel: "BIR Tax Tracker",
      },
      {
        id: "sss",
        title: "Register with SSS",
        description: "The Social Security System provides retirement pension, disability, maternity, sickness, and death benefits — plus salary and calamity loans.",
        why: "SSS is mandatory for all employees and voluntary for self-employed/OFWs. Your SSS number is required to be hired. Benefits compound over a lifetime of contributions — the more you put in, the higher your pension.",
        how: "Register online at my.sss.gov.ph with a valid ID and submit BIR Form SS-1. Your employer should process this for you if you're formally employed. After 36 monthly contributions, you can apply for a physical SS card or UMID.",
        priority: "critical",
        appLink: "/adulting/contributions",
        appLinkLabel: "Contributions Tracker",
      },
      {
        id: "philhealth",
        title: "Register with PhilHealth",
        description: "PhilHealth covers inpatient hospitalization, day surgery, outpatient consultations, and selected medicines through its benefits packages.",
        why: "A single hospitalization without PhilHealth coverage can cost ₱50,000–₱200,000+. PhilHealth significantly reduces your out-of-pocket expenses. Mandatory for employees; voluntary for self-employed and OFWs.",
        how: "If employed: employer enrolls you. Self-employed: register at the nearest PhilHealth office or through PhilSys. Bring a valid ID and complete PMRF (PhilHealth Member Registration Form). Check your contributions at philhealth.gov.ph.",
        priority: "critical",
        appLink: "/adulting/contributions",
        appLinkLabel: "Contributions Tracker",
      },
      {
        id: "pagibig",
        title: "Register with Pag-IBIG (HDMF)",
        description: "Pag-IBIG provides housing loans, multi-purpose loans, and the MP2 savings program that earns 6–7% tax-free dividends annually.",
        why: "Mandatory for employees. The MP2 program alone consistently outperforms bank savings rates at 6–7% per year, fully tax-free. After 24 months of contributions, you're eligible for housing loans up to ₱6,000,000.",
        how: "Register at Virtual Pag-IBIG (pagibig-fund.gov.ph) or visit a branch. Bring a valid ID and fill out the Membership Registration Form (MRF). Employer handles mandatory contributions from payroll.",
        priority: "critical",
        appLink: "/adulting/contributions",
        appLinkLabel: "Contributions Tracker",
      },
      {
        id: "philsys",
        title: "Get your PhilSys National ID",
        description: "The Philippine Identification System (PhilSys) card is the government's official national ID, designed to replace the need for multiple IDs.",
        why: "Once fully rolled out, it will be universally accepted for all government and private transactions. It's free, biometric-linked, and shows your PhilSys Number (PSN) — your permanent identity number.",
        how: "Schedule a Step 2 registration at philsys.gov.ph or walk in to a PSA registration center. Bring your birth certificate and proof of address. The card is mailed to your registered address.",
        priority: "critical",
      },
      {
        id: "umid",
        title: "Apply for your UMID Card",
        description: "The Unified Multi-Purpose ID combines your SSS, PhilHealth, Pag-IBIG, and GSIS membership into one card accepted everywhere.",
        why: "The UMID is one of the most widely accepted government IDs in the Philippines — banks, offices, even airports. It also functions as an ATM card for SSS benefits and loans.",
        how: "Apply at any SSS branch with at least one posted SSS contribution. Fill out the UMID card application form, provide biometrics (photo, fingerprint, signature). Processing takes about 4–8 weeks.",
        priority: "important",
      },
      {
        id: "passport",
        title: "Get a Philippine Passport",
        description: "Your passport is the most universally accepted ID in the Philippines and the world — it's your key to international travel.",
        why: "Even if you don't plan to travel abroad soon, having a passport gives you the most powerful ID for banking, visa applications, and official transactions. Valid for 10 years (adults).",
        how: "Schedule an appointment at dfa.gov.ph/passport. Prepare: PSA birth certificate, valid government ID, accomplished application form. Processing is 12 business days (regular) or 6 days (expedited). Cost: ₱950 (regular) or ₱1,200 (expedited).",
        priority: "important",
      },
      {
        id: "drivers-license",
        title: "Get a Driver's License (LTO)",
        description: "A non-professional driver's license lets you legally drive a private vehicle and is a widely accepted government ID.",
        why: "Required by law to drive. Also one of the most accepted IDs for banking and government transactions. Valid for 5 years.",
        how: "Step 1: Get a Student Permit at LTO — bring PSA birth certificate, valid ID, medical certificate, and pass the written exam. Step 2: After holding a student permit, apply for a non-professional license with a practical driving test. Process at lto.gov.ph or any LTO office.",
        priority: "good-to-have",
      },
      {
        id: "voters-id",
        title: "Register as a Voter (COMELEC)",
        description: "Voter registration gives you the right to vote in national and local elections — and your voter's certificate is accepted as a valid ID.",
        why: "Voting is your civic duty and your voice in shaping the Philippines. Local elections directly affect your community, schools, roads, and health services. Registration is free.",
        how: "Register at the COMELEC office in your municipality/city. Bring a valid ID and proof of residency. Online pre-registration is available at voterregistration.comelec.gov.ph. Registration periods open before every election.",
        priority: "important",
      },
    ],
  },
  {
    id: "banking",
    number: 2,
    title: "Banking & Emergency Fund",
    subtitle: "Set up your financial infrastructure.",
    color: "text-emerald-600 dark:text-emerald-400",
    bg: "bg-emerald-500/10",
    borderColor: "border-emerald-500/30",
    items: [
      {
        id: "savings-account",
        title: "Open a bank savings account",
        description: "A traditional savings account at BDO, BPI, Metrobank, or UnionBank gives you access to ATMs nationwide, checks, and formal banking services.",
        why: "Cash under a mattress earns nothing and can be stolen. A savings account is the baseline for receiving payroll, paying bills, and accessing the financial system. Required for most loan applications.",
        how: "Visit any branch with two valid IDs and an initial deposit (BPI: ₱3,000; BDO: ₱2,000; UnionBank: ₱0). UnionBank's EON account and BDO's account can be opened fully online. Choose a bank near your home or office.",
        priority: "critical",
        appLink: "/accounts",
        appLinkLabel: "Track in Accounts",
      },
      {
        id: "digital-savings",
        title: "Open a high-yield digital savings account",
        description: "ING (4% p.a.), CIMB (4.5% p.a.), and Maya (3.5% p.a.) offer savings rates far above traditional banks, with no maintaining balance.",
        why: "Traditional banks pay 0.10–0.25% interest. Digital banks pay 3–5%. On ₱50,000 in emergency funds, that's the difference between ₱125/year vs. ₱2,000/year — with zero maintaining balance.",
        how: "Download the app: ING Philippines, CIMB Bank, Maya, or Tonik. Sign up with a selfie + valid ID (passport or PhilSys). Account opens in minutes. Transfer money via InstaPay (₱50 fee, unless free with your sending bank).",
        priority: "important",
        appLink: "/accounts",
        appLinkLabel: "Track in Accounts",
      },
      {
        id: "emergency-fund-3mo",
        title: "Save 3 months of living expenses",
        description: "Your emergency fund covers job loss, medical emergencies, car repairs, or any unexpected expense — without going into debt.",
        why: "Without an emergency fund, any unexpected expense forces you to borrow (credit card, 5-6 loan). The average Filipino salary takes 3–6 months to find a new job. Your emergency fund is your self-insurance.",
        how: "Calculate your monthly expenses (rent + food + transport + utilities + insurance). Multiply by 3. Keep this in a separate high-yield savings account — don't mix it with your spending money. Automate a monthly transfer.",
        priority: "critical",
        appLink: "/goals",
        appLinkLabel: "Set Goal",
      },
      {
        id: "understand-payslip",
        title: "Understand your payslip deductions",
        description: "Know exactly what SSS, PhilHealth, Pag-IBIG, and withholding tax amounts are being deducted from your salary every month.",
        why: "Many Filipinos don't know what they're actually earning vs. what's being withheld. Understanding deductions lets you verify your contributions are correct and plan your net take-home budget accurately.",
        how: "Check your payslip monthly. Verify SSS, PhilHealth, and Pag-IBIG amounts match the official tables. Withholding tax depends on your salary bracket. Use ExitPlan's Contribution Calculator to verify your employer is computing correctly.",
        priority: "critical",
        appLink: "/adulting/contributions",
        appLinkLabel: "Calculate Deductions",
      },
      {
        id: "credit-card",
        title: "Get a credit card (responsibly)",
        description: "A credit card builds your credit history, earns rewards/cashback, and provides a safety net — only if you pay the full balance every month.",
        why: "Credit cards are a tool, not free money. Paying in full every month costs you nothing (0% effective rate) and earns rewards. Minimum payments trap you in 24–36% annual interest — the single worst financial mistake Filipinos make.",
        how: "Apply at BPI (Amore), BDO (Visa Classic), or Security Bank (Complete Cashback). Requirements: Certificate of Employment, 2 months payslips, TIN, and 1 valid ID. Start with a low limit. Golden rule: never charge what you can't pay by billing date.",
        priority: "good-to-have",
      },
    ],
  },
  {
    id: "contributions",
    number: 3,
    title: "Government Contributions",
    subtitle: "Protect your future self — these are mandatory benefits, not just taxes.",
    color: "text-violet-600 dark:text-violet-400",
    bg: "bg-violet-500/10",
    borderColor: "border-violet-500/30",
    items: [
      {
        id: "sss-active",
        title: "Verify your SSS contributions are current",
        description: "Check your SSS contribution history to make sure your employer is remitting your deductions and that your records are accurate.",
        why: "Some employers deduct SSS but fail to remit — leaving you with gaps in your contribution history that affect your loan eligibility and eventual pension. You are entitled to sue your employer for this.",
        how: "Log in to my.sss.gov.ph → Contributions. Verify each month shows up. If a month is missing and you were employed, file a complaint with SSS. Keep payslip records as proof of your deductions.",
        priority: "critical",
        appLink: "/adulting/contributions",
        appLinkLabel: "Track Contributions",
      },
      {
        id: "philhealth-active",
        title: "Verify your PhilHealth contributions are current",
        description: "Check that your employer is remitting your PhilHealth contributions and that your membership is active for hospitalization benefits.",
        why: "If contributions aren't posted, you won't be able to use PhilHealth benefits when hospitalized. Members without active contributions may need to pay a differential fee to avail coverage.",
        how: "Log in to PhilHealth member portal at philhealth.gov.ph → Contributions. Check for gaps. Your employer should give you an MDR (Member Data Record) confirming active status. For outpatient: present PhilHealth ID and MDR at accredited facilities.",
        priority: "critical",
        appLink: "/adulting/contributions",
        appLinkLabel: "Track Contributions",
      },
      {
        id: "pagibig-active",
        title: "Verify your Pag-IBIG contributions are current",
        description: "Confirm monthly Pag-IBIG deductions are being remitted so your housing loan eligibility and MP2 savings are properly building.",
        why: "24 months of Pag-IBIG contributions makes you eligible for housing loans. If your employer isn't remitting, you lose eligibility and your contributions may not count.",
        how: "Log in at pagibig-fund.gov.ph → Virtual Pag-IBIG → Member's Contribution History. Or text PAG-IBIG <MID number> to 4643. Contact your HR if months are missing.",
        priority: "critical",
        appLink: "/adulting/contributions",
        appLinkLabel: "Track Contributions",
      },
      {
        id: "13th-month",
        title: "Know your 13th month pay rights",
        description: "All rank-and-file employees are legally entitled to 13th month pay — at least 1/12 of your basic annual salary, paid on or before December 24.",
        why: "It's not a bonus — it's the law (Presidential Decree No. 851). Up to ₱90,000 is tax-exempt. Some employers try to include it in monthly salary ('already included') which is illegal. Know your rights.",
        how: "Formula: (Total Basic Salary Earned in a Year) ÷ 12. Compute yours in ExitPlan. If you think you were underpaid, file a complaint with DOLE (Department of Labor and Employment). Must be paid regardless of resignation or separation.",
        priority: "critical",
        appLink: "/adulting/thirteenth-month",
        appLinkLabel: "13th Month Calculator",
      },
    ],
  },
  {
    id: "tax",
    number: 4,
    title: "Tax Compliance",
    subtitle: "File correctly, avoid penalties, and never pay more than you owe.",
    color: "text-orange-600 dark:text-orange-400",
    bg: "bg-orange-500/10",
    borderColor: "border-orange-500/30",
    items: [
      {
        id: "bir-2316",
        title: "Get your BIR Form 2316 from your employer",
        description: "Form 2316 is the Certificate of Compensation Payment and Tax Withheld — proof of your income and taxes paid, issued by your employer every January.",
        why: "This document proves your tax was withheld correctly. You need it for loan applications (housing, bank), new employer onboarding, and to verify your annual tax was properly settled. Never lose it.",
        how: "Ask HR or payroll every January for your 2316 covering the previous year. If your employer failed to issue one, they're violating the Tax Code. Scan it and keep a digital copy. Most employers issue it by January 31.",
        priority: "critical",
        appLink: "/adulting/taxes",
        appLinkLabel: "BIR Tax Tracker",
      },
      {
        id: "substituted-filing",
        title: "Know if you need to file an ITR yourself",
        description: "Most pure employees with one employer qualify for Substituted Filing — meaning your employer files on your behalf and you don't need to file Form 1700.",
        why: "Filing when not required wastes time. NOT filing when required leads to penalties of 25% surcharge + 12% interest per year + ₱1,000 compromise penalty. Know your classification.",
        how: "You don't need to file if: single employer, compensation income only, tax was correctly withheld, employer files BIR Alphalist. You MUST file (Form 1700) if: two or more employers in a year, business income, compensation exceeds ₱2.4M, or you want a tax refund.",
        priority: "critical",
        appLink: "/adulting/taxes",
        appLinkLabel: "BIR Tax Tracker",
      },
      {
        id: "bir-freelancer",
        title: "Register with BIR as freelancer or self-employed",
        description: "If you have any income outside of a formal employer — freelancing, consulting, online selling, or a side business — you must register with BIR.",
        why: "Unregistered businesses and freelancers face back taxes, 25% surcharge, 12% annual interest, and compromise penalties going back 3–10 years. The BIR has been actively running after digital earners and influencers.",
        how: "File BIR Form 1901 at your RDO with TIN, proof of business address, and valid ID. Register your books of accounts. Print Official Receipts (ORs) or use the eBIRForms system. Annual registration fee: ₱500. File quarterly (1701Q) and annual (1701/1701A) ITR.",
        priority: "critical",
        appLink: "/adulting/taxes",
        appLinkLabel: "BIR Tax Tracker",
      },
      {
        id: "bir-deductions",
        title: "Know your allowable deductions",
        description: "Self-employed individuals can deduct business expenses OR choose the Optional Standard Deduction (OSD) of 40% of gross income — whichever lowers your tax more.",
        why: "Many self-employed Filipinos overpay because they don't know they can deduct internet, phone, home office, transportation, professional development, and health insurance premiums from their taxable income.",
        how: "Keep receipts for all business-related expenses. If expenses exceed 40% of income, itemize. If not, use OSD. Also consider the 8% flat income tax option if gross sales/receipts are below ₱3,000,000 — often simpler and lower than graduated rates.",
        priority: "important",
        appLink: "/adulting/taxes",
        appLinkLabel: "BIR Tax Tracker",
      },
    ],
  },
  {
    id: "insurance",
    number: 5,
    title: "Insurance & Protection",
    subtitle: "Don't let one bad event wipe out everything you've built.",
    color: "text-teal-600 dark:text-teal-400",
    bg: "bg-teal-500/10",
    borderColor: "border-teal-500/30",
    items: [
      {
        id: "philhealth-benefits",
        title: "Learn how to actually use your PhilHealth",
        description: "Knowing how to use your PhilHealth benefits can save you tens of thousands of pesos during hospitalization — most members don't claim what they're entitled to.",
        why: "PhilHealth covers specific amounts per diagnosis (case rate) regardless of actual hospital bill. For normal delivery alone it covers ₱6,500. Without knowing how to file, you leave money on the table.",
        how: "Present PhilHealth ID + MDR at accredited hospital admission. The hospital files PhilHealth claims on your behalf. For outpatient: Z-benefits cover cancer, dialysis, and selected conditions. Check philhealth.gov.ph/services for the full benefits table.",
        priority: "critical",
        appLink: "/adulting/insurance",
        appLinkLabel: "Insurance Tracker",
      },
      {
        id: "hmo",
        title: "Get HMO coverage",
        description: "An HMO (Health Maintenance Organization) covers outpatient consultations, diagnostics, and emergency room visits that PhilHealth doesn't fully cover.",
        why: "PhilHealth mostly covers inpatient care. A single ER visit, lab workup, or specialist consultation can cost ₱2,000–₱10,000 out of pocket. HMO fills this gap. Company HMO is free — always enroll in it if offered.",
        how: "If employed: enroll in your company's HMO during open enrollment — it's usually free or subsidized. If self-employed: personal plans from Maxicare, Medicard, or Intellicare start at ~₱3,000–₱8,000/year. Compare online at HMO comparison sites.",
        priority: "critical",
        appLink: "/adulting/insurance",
        appLinkLabel: "Insurance Tracker",
      },
      {
        id: "life-insurance",
        title: "Get term life insurance",
        description: "Term life insurance pays your beneficiaries a lump sum if you die during the coverage period — pure protection with no investment component.",
        why: "If anyone depends on your income (parents, spouse, kids), you need life insurance. Rule of thumb: 10x your annual income in coverage. Term insurance is 3–5x cheaper than VUL for the same coverage. Most Filipinos are oversold VULs when term would serve them better.",
        how: "Get term insurance first: PRULife's PRUTerm One, Sun Life's SunTerm, or AXA's FlexiProtect. Annual premiums for ₱1,000,000 coverage start around ₱3,000–₱5,000/year for a healthy 25-year-old. Avoid mixing insurance with investment (VUL) until you fully understand both.",
        priority: "important",
        appLink: "/adulting/insurance",
        appLinkLabel: "Insurance Tracker",
      },
      {
        id: "ctpl",
        title: "CTPL: Mandatory vehicle insurance",
        description: "Compulsory Third Party Liability (CTPL) insurance is required by law for all motor vehicle registrations at LTO. No CTPL = no LTO sticker.",
        why: "CTPL covers bodily injury or death to third parties in road accidents — not your own vehicle. It's the minimum legal requirement. Driving without valid LTO registration (which requires CTPL) is a criminal offense.",
        how: "Buy CTPL from any insurance company accredited by LTO: COCOGEN, Malayan, Charter Ping An, etc. 1-year coverage costs ~₱400–₱800. Purchase at LTO during registration renewal, at authorized payment centers, or online through Gcash/Maya.",
        priority: "important",
        appLink: "/adulting/insurance",
        appLinkLabel: "Insurance Tracker",
      },
    ],
  },
  {
    id: "investing",
    number: 6,
    title: "Investing & Building Wealth",
    subtitle: "Make your money work — after your foundation is solid.",
    color: "text-amber-600 dark:text-amber-400",
    bg: "bg-amber-500/10",
    borderColor: "border-amber-500/30",
    items: [
      {
        id: "emergency-fund-6mo",
        title: "Build a full 6-month emergency fund",
        description: "Expand your emergency fund to cover 6 months of living expenses — especially if you're self-employed or in an industry with high job instability.",
        why: "3 months is the minimum. 6 months is the real target — especially for freelancers, commission-based workers, or those with dependents. This is the foundation; you should not invest until this is done.",
        how: "Calculate: monthly expenses × 6. Keep in a separate high-yield savings account (ING, CIMB). Don't invest this money — it must be liquid and immediately accessible. Top it up if you ever tap it.",
        priority: "critical",
        appLink: "/goals",
        appLinkLabel: "Set Goal",
      },
      {
        id: "mp2",
        title: "Start Pag-IBIG MP2 savings",
        description: "Modified Pag-IBIG II is a voluntary savings program that earns 6–7% annual dividends, fully tax-free — one of the best guaranteed returns in the Philippines.",
        why: "MP2 consistently outperforms most bank time deposits and UITFs with much lower risk. It's government-guaranteed. The 5-year maturity is flexible — you can withdraw dividends annually or let them compound.",
        how: "Log in to Virtual Pag-IBIG → MP2 Enrollment. Minimum: ₱500/month or lump sum ₱500. Set up auto-debit from your bank account. After 5 years, you can withdraw the entire principal + dividends or roll over for another 5 years.",
        priority: "important",
        appLink: "/goals",
        appLinkLabel: "Track Savings Goal",
      },
      {
        id: "uitf",
        title: "Open a UITF or mutual fund account",
        description: "Unit Investment Trust Funds (UITFs) pool money from many investors to invest in bonds, equities, or a mix — professionally managed with as little as ₱1,000.",
        why: "Higher long-term returns than savings accounts (equity UITFs historically return 8–12% annually). You can start small, invest regularly, and not need to pick individual stocks. Good for 5–10+ year goals.",
        how: "Open through your existing bank: BDO, BPI, or UnionBank UITFs can be started online. Choose based on risk: Money Market (lowest) → Bond → Balanced → Equity (highest). Start with ₱1,000. Read the Key Information Document (KID) before investing.",
        priority: "important",
        appLink: "/goals",
        appLinkLabel: "Track Investment Goal",
      },
      {
        id: "stocks-pse",
        title: "Learn about the Philippine Stock Exchange",
        description: "Investing in PSE-listed companies lets you own a piece of SM, Ayala, JG Summit, BDO, and others — with the potential for long-term wealth creation.",
        why: "The PSE has historically returned 8–12% annually over 10+ year periods. Dividends provide passive income. Owning blue-chip stocks is a proven long-term wealth strategy — but requires patience and a 10+ year mindset.",
        how: "Open an account with COL Financial (easiest for beginners), BDO Nomura, or First Metro Securities. Minimum: ₱1,000 with COL. Start with blue-chip stocks: SM, Ayala Land, BDO, BPI, Jollibee. Never invest money you need within 5 years.",
        priority: "good-to-have",
        appLink: "/goals",
        appLinkLabel: "Track Investment Goal",
      },
      {
        id: "sss-voluntary",
        title: "Make voluntary SSS contributions to increase your pension",
        description: "The maximum monthly SSS pension is tied to your Monthly Salary Credit (MSC). Higher contributions = higher pension. You can voluntarily contribute above the minimum.",
        why: "The default SSS pension for minimum-wage workers can be as low as ₱1,500–₱2,000/month — far below the poverty line. Increasing your MSC now dramatically increases your future retirement pension.",
        how: "Log in to my.sss.gov.ph → Payment Reference Number (PRN) → select voluntary contribution amount. You can contribute up to the maximum MSC of ₱30,000. Payments via GCash, online banking, or SSS-accredited payment centers.",
        priority: "good-to-have",
        appLink: "/adulting/contributions",
        appLinkLabel: "Contributions Tracker",
      },
    ],
  },
  {
    id: "estate",
    number: 7,
    title: "Estate & Legacy Planning",
    subtitle: "Protect your family even when you're no longer there.",
    color: "text-slate-600 dark:text-slate-400",
    bg: "bg-slate-500/10",
    borderColor: "border-slate-500/30",
    items: [
      {
        id: "beneficiaries",
        title: "Update beneficiaries on all accounts",
        description: "Make sure your SSS, PhilHealth, Pag-IBIG, bank accounts, and insurance policies have updated and correct beneficiaries.",
        why: "Without designated beneficiaries, death benefits get tied up in lengthy legal proceedings. Courts, lawyers, and estate taxes can eat up to 20–30% of what you leave behind. A simple form update can save your family years of grief.",
        how: "SSS: Update E-4 form at any SSS branch. Pag-IBIG: Submit MDF (Membership Data Form) at a branch. Banks: Ask for beneficiary designation forms — most banks offer this. Insurance: Call your insurance provider or go to their office.",
        priority: "important",
      },
      {
        id: "will",
        title: "Create a basic last will and testament",
        description: "A notarized will ensures your assets go where you want them to, protects your family from succession disputes, and makes the estate settlement process faster.",
        why: "Without a will, Philippine intestate law distributes your estate according to the Civil Code — which may not match your wishes. Family disputes over inheritance are common and devastating. A will minimizes conflict.",
        how: "Hire a lawyer to draft a notarial will (most affordable: ₱3,000–₱8,000 with a notary). Alternatively, a holographic will (handwritten, dated, signed) is valid in the Philippines with no notarization needed. Keep the original in a safe place; give a copy to a trusted person.",
        priority: "good-to-have",
      },
      {
        id: "estate-tax",
        title: "Understand estate tax",
        description: "When you pass away, the Philippine government imposes a 6% estate tax on the net estate above ₱5,000,000 — paid before heirs can claim assets.",
        why: "Many Filipino families lose portions of their inheritance because they don't understand estate taxes or can't afford to pay them. Prior planning (insurance, proper titling, estate tax amnesty) can significantly reduce this burden.",
        how: "The estate tax return (BIR Form 1801) must be filed within 1 year of death. Consider estate tax insurance — a life insurance policy sized to cover anticipated estate taxes. Keep property titles, bank records, and key documents organized and accessible to heirs.",
        priority: "good-to-have",
      },
    ],
  },
];

export const ALL_ITEMS = CHECKLIST_PHASES.flatMap((p) => p.items);

export const TOTAL_ITEMS = ALL_ITEMS.length;

export const PRIORITY_META: Record<ChecklistPriority, { label: string; color: string; bg: string }> = {
  critical: { label: "Must Do", color: "text-red-600 dark:text-red-400", bg: "bg-red-500/10" },
  important: { label: "Should Do", color: "text-amber-600 dark:text-amber-400", bg: "bg-amber-500/10" },
  "good-to-have": { label: "Nice to Have", color: "text-blue-600 dark:text-blue-400", bg: "bg-blue-500/10" },
};
